Repository alphagov/govuk-frontend, pull requests merged in 2018-07, with the labels that each got.

#863 Set display:block on `main` wrapper
  CHANGELOG.md
  src/objects/_main-wrapper.scss
Labels: fix

#853 Allow the panel component title heading level to be customisable
  CHANGELOG.md
  src/components/panel/README.md
  src/components/panel/README.njk
  src/components/panel/panel.yaml
  src/components/panel/template.njk
  src/components/panel/template.test.js
Labels: enhancement

#849 Allow for an optional divider between radio items
  CHANGELOG.md
  src/components/radios/README.md
  src/components/radios/README.njk
  src/components/radios/_radios.scss
  src/components/radios/radios.yaml
  src/components/radios/template.njk
  src/components/radios/template.test.js
Labels: feature

#847 Allow og:image meta tag to be customisable
  CHANGELOG.md
  src/template.njk
Labels: feature

#885 Fix flash of unstyled content with conditional reveals
  CHANGELOG.md
  src/components/checkboxes/_checkboxes.scss
  src/components/checkboxes/checkboxes.js
  src/components/checkboxes/checkboxes.test.js
  src/components/checkboxes/template.njk
  src/components/checkboxes/template.test.js
  src/components/radios/_radios.scss
  src/components/radios/radios.js
  src/components/radios/radios.test.js
  src/components/radios/template.njk
  src/components/radios/template.test.js
Labels: bug

#846 Allow an optional hint for each radio and checkbox item
  CHANGELOG.md
  src/components/checkboxes/README.md
  src/components/checkboxes/README.njk
  src/components/checkboxes/_checkboxes.scss
  src/components/checkboxes/checkboxes.yaml
  src/components/checkboxes/template.njk
  src/components/checkboxes/template.test.js
  src/components/radios/README.md
  src/components/radios/README.njk
  src/components/radios/_radios.scss
  src/components/radios/radios.yaml
  src/components/radios/template.njk
  src/components/radios/template.test.js
Labels: feature

#880 Allow additional label classes in radios and checkboxes macros
  CHANGELOG.md
  src/components/checkboxes/README.md
  src/components/checkboxes/README.njk
  src/components/checkboxes/template.njk
  src/components/checkboxes/template.test.js
  src/components/radios/README.md
  src/components/radios/README.njk
  src/components/radios/template.njk
  src/components/radios/template.test.js
Labels: feature
