Repository alphagov/govuk-frontend, pull requests merged in 2021-08, with the labels that each got.

#2292 Add page-checking bookmarklet info to testing doc
  docs/contributing/testing.md
Labels: 2i, documentation, 🕔 hours

#2297 Fix typo in fieldset macros
  src/govuk/components/fieldset/fieldset.yaml
Labels: documentation

#2304 Create resize-text-in-browsers.md
  docs/contributing/resize-text-in-browsers.md
Labels: documentation, 🕔 hours

#2305 Add link from testing doc to resize-text doc
  docs/contributing/testing.md
Labels: documentation, 🕔 hours

#2308 Fix American English in Sass docs Colour section
  src/govuk/helpers/_colour.scss
Labels: documentation

#2312 Remove padding-right from details element
  CHANGELOG.md
  src/govuk/components/details/_index.scss
Labels: 🕔 hours, design
