Repository alphagov/govuk-frontend, pull requests merged in 2021-11, with the labels that each got.

#2257 Update Accordion design
  app/views/full-page-examples/campaign-page/index.njk
  src/govuk/components/accordion/_index.scss
  src/govuk/components/accordion/accordion.js
  src/govuk/components/accordion/accordion.test.js
  src/govuk/components/accordion/accordion.yaml
  src/govuk/components/accordion/template.test.js
Labels: breaking change, accessibility, accordion

#2424 Add punctuation to Frontend Changelog
  CHANGELOG.md
Labels: documentation

#2313 Update accordion macros about summary line change
  src/govuk/components/accordion/accordion.yaml
Labels: documentation, 🕔 hours, accordion, 2i

#2415 Add documentation for releasing GOV.UK Frontend from a support branch
  docs/releasing/publishing-from-a-support-branch.md
Labels: documentation

#2410 Add accordion changes content to Changelog
  CHANGELOG.md
Labels: documentation, accordion

#2405 Tell users how to report inappropriate content
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation, 🕔 days, guidance, 2i, security

#2433 Update changelog based on user feedback
  CHANGELOG.md
Labels: documentation

#2440 Add correct PR link to changelog
  CHANGELOG.md
Labels: documentation

#2443 Add headings and 2i approved text to release doc
  docs/releasing/publishing.md
Labels: documentation

#2445 Footer alignment example should use full width layout
  app/views/examples/footer-alignment/index.njk
Labels: examples, footer

#2444 Add npm credentials to support branch doc
  docs/releasing/publishing-from-a-support-branch.md
Labels: documentation
