Repository alphagov/govuk-frontend, pull requests merged in 2021-09, with the labels that each got.

#2326 Document how to initialise JS and target elements
  docs/contributing/coding-standards/js.md
Labels: documentation

#2335 Add correct links in css md and improve wording
  docs/contributing/coding-standards/css.md
Labels: documentation, 🕔 hours, small story

#2329 Add release notes for Frontend v3.13.1 release
  CHANGELOG.md
Labels: documentation, colour, 🚀 release, 2i

#2356 Add document for testing component accessibility
  docs/contributing/test-components-using-accessibility-acceptance-criteria.md
Labels: documentation, accessibility, ⚠️ high priority, 🕔 weeks

#2353 Add cookie banner examples using `headingHtml` and `html`
  app/views/full-page-examples/cookie-banner-client-side/index.njk
  src/govuk/components/cookie-banner/cookie-banner.yaml
Labels: examples, cookie banner

#2372 Link Frontend repo README to security policy
  README.md
Labels: documentation, 🕔 hours, small story
