Repository alphagov/govuk-frontend, pull requests merged in 2021-04, with the labels that each got.

#2176 Replace inaccessible text in text input macros
  src/govuk/components/input/input.yaml
Labels: documentation, 🕔 hours

#2174 Update release process to guide team practice
  docs/releasing/publishing.md
Labels: documentation, 🕔 days

#2202 Add consistent terminology to cookie banner macros
  src/govuk/components/cookie-banner/cookie-banner.yaml
Labels: documentation

#2205 Stop file upload component 'jumping' on focus
  CHANGELOG.md
  src/govuk/components/file-upload/_index.scss
Labels: file upload, 🐛 bug
