Repository alphagov/govuk-frontend, pull requests merged in 2021-12, with the labels that each got.

#2451 Apply code formatting to mention of data-nosnippet
  CHANGELOG.md
Labels: documentation

#2454 Add contributor names to draft release notes
  CHANGELOG.md
Labels: documentation

#2452 Update error messages to use paragraph tags instead of spans
  CHANGELOG.md
  src/govuk/components/character-count/__snapshots__/template.test.js.snap
  src/govuk/components/checkboxes/__snapshots__/template.test.js.snap
  src/govuk/components/date-input/__snapshots__/template.test.js.snap
  src/govuk/components/error-message/_index.scss
  src/govuk/components/error-message/template.njk
  src/govuk/components/file-upload/__snapshots__/template.test.js.snap
  src/govuk/components/input/__snapshots__/template.test.js.snap
  src/govuk/components/radios/__snapshots__/template.test.js.snap
  src/govuk/components/select/__snapshots__/template.test.js.snap
  src/govuk/components/textarea/__snapshots__/template.test.js.snap
Labels: breaking change, error message

#2464 Add thanks to accordion contributors to changelog
  CHANGELOG.md
Labels: documentation, 🚀 release

#2473 Add 2i-approved release notes content to changelog
  CHANGELOG.md
Labels: documentation, 🚀 release, 2i

#2475 Tweak whitespace in input component HTML for improved readability
  CHANGELOG.md
  src/govuk/components/input/template.njk
Labels: text input
