Repository alphagov/govuk-frontend, pull requests merged in 2021-06, with the labels that each got.

#2251 Disable ink skipping for underlines in hover state
  CHANGELOG.md
  src/govuk/helpers/_links.scss
  src/govuk/helpers/links.test.js
Labels: typography

#2252 Update release notes for v3.13.0 release
  CHANGELOG.md
Labels: documentation, 🕔 hours

#2262 Clarify which npm user to login with for releases
  docs/releasing/publishing.md
Labels: documentation
