Repository alphagov/govuk-frontend, pull requests merged in 2022-04, with the labels that each got.

#2590 Maxlength attribute should not be present on textarea after character-count JavaScript has kicked in
  CHANGELOG.md
  src/govuk/components/character-count/character-count.js
  src/govuk/components/character-count/character-count.test.js
  src/govuk/components/character-count/character-count.yaml
Labels: 🐛 bug, character count

#2574 Update Node to Active LTS version v16 (Gallium)
  .nvmrc
  docs/contributing/running-locally.md
  package-lock.json
  package.json
Labels: documentation, tooling, dependencies

#2604 Update card title in changelog
  CHANGELOG.md
Labels: documentation

#2600 Update publishing doc card examples
  docs/releasing/publishing.md
Labels: documentation

#2605 Replace card with issue in support branch doc
  docs/releasing/publishing-from-a-support-branch.md
Labels: documentation
