Repository alphagov/govuk-frontend, pull requests merged in 2022-11, with the labels that each got.

#2951 Fix docs broken links, lint changes, trailing spaces
  docs/contributing/coding-standards/css.md
  docs/contributing/coding-standards/js.md
  docs/contributing/tasks.md
  docs/contributing/test-components-using-accessibility-acceptance-criteria.md
  docs/contributing/testing.md
  docs/contributing/versioning.md
  docs/releasing/testing-and-linting.md
  package/README.md
Labels: documentation

#2946 Adjust path handling (+ tests) for Windows compatibility
  app/app.js
  app/app.test.js
  gulpfile.js
  lib/file-helper.js
  package-lock.json
  package.json
  postcss.config.js
  src/govuk/components/all.test.js
  src/govuk/components/components.template.test.js
  src/govuk/components/components.test.js
  src/govuk/helpers/helpers.test.js
  src/govuk/objects/objects.test.js
  src/govuk/settings/settings.test.js
  src/govuk/tools/tools.test.js
  tasks/asset-version.js
  tasks/gulp/__tests__/after-build-dist.test.js
  tasks/gulp/__tests__/after-build-package.test.js
  tasks/gulp/compile-assets.js
  tasks/gulp/copy-to-destination.js
Labels: tooling, Frontend squad

#2938 Add `cross-env-shell` for Windows support
  config/jest/server/start.mjs
Labels: 🕔 hours, tooling, Frontend squad

#2851 Supporting v13 of the Prototype Kit
  docs/contributing/tasks.md
  gulpfile.js
  package/govuk-prototype-kit.config.json
  src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
  src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs
  src/govuk-prototype-kit/init.js
  src/govuk-prototype-kit/init.scss
  tasks/gulp/__tests__/after-build-package.test.js
  tasks/prototype-kit-config.js
Labels: feature request, Frontend squad

#2950 Update all dependencies using Dependabot
  .github/dependabot.yml
Labels: 🕔 hours, tooling, dependencies, Frontend squad

#2962 Use absolute directory paths everywhere
  app/app.js
  config/paths.js
  gulpfile.js
  lib/file-helper.js
  lib/jest-helpers.js
  src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
  src/govuk/all.test.js
  src/govuk/components/components.template.test.js
  src/govuk/helpers/helpers.test.js
  src/govuk/objects/objects.test.js
  src/govuk/settings/colours.test.js
  src/govuk/settings/settings.test.js
  src/govuk/template.test.js
  src/govuk/tools/tools.test.js
  tasks/asset-version.js
  tasks/clean.js
  tasks/gulp/__tests__/after-build-dist.test.js
  tasks/gulp/__tests__/after-build-package.test.js
  tasks/gulp/compile-assets.js
  tasks/gulp/copy-to-destination.js
  tasks/gulp/watch.js
  tasks/prototype-kit-config.js
  tasks/task-arguments.js
  tasks/task-arguments.unit.test.js
Labels: consistency, Frontend squad

#2964 Update `copy:files` to glob “src” not “src/govuk”
  tasks/gulp/copy-to-destination.js
  tasks/prototype-kit-config.js
Labels: tooling, Frontend squad

#2992 Enable `package.json` updates for Dependabot
  .github/dependabot.yml
Labels: Frontend squad

#2981 Add changelog entry for prototype kit config build
  CHANGELOG.md
Labels: Frontend squad

#2993 Package updates
  config/jest/environment/node.mjs
  docs/examples/webpack/package.json
  jest.config.js
  package-lock.json
  package.json
Labels: dependencies, Frontend squad

#2997 Various JSDoc + type checking fixes (for v4.4.0 only)
  jsdoc.config.js
  src/govuk/all.mjs
  src/govuk/components/accordion/accordion.mjs
  src/govuk/components/button/button.mjs
  src/govuk/components/character-count/character-count.mjs
  src/govuk/components/character-count/character-count.test.js
  src/govuk/components/character-count/character-count.unit.test.mjs
  src/govuk/components/error-summary/error-summary.mjs
  src/govuk/components/notification-banner/notification-banner.mjs
  src/govuk/i18n.mjs
  src/govuk/i18n.unit.test.mjs
Labels: Frontend squad

#3004 Set up review app `package.json` (12MB install)
  app.json
  app/app.js
  app/middleware/assets.js
  app/middleware/index.js
  app/middleware/vendor.js
  app/nodemon.json
  app/package.json
  gulpfile.js
  lib/helper-functions.js
  package-lock.json
  package.json
  package.json.unit.test.js
Labels: Frontend squad

#3009 Send Percy screenshots via npm script (not Jest)
  .github/workflows/tests.yml
  docs/releasing/testing-and-linting.md
  lib/puppeteer-helpers.js
  package-lock.json
  package.json
  src/govuk/components/all.test.js
  tasks/screenshot-components.mjs
Labels: Frontend squad

#3019 Switch review app to Heroku-22 stack (Ubuntu-22.04 LTS)
  app.json
Labels: tech debt, Frontend squad

#3028 Skip “Percy screenshots” when secrets are unavailable on forks
  .github/workflows/screenshots.yml
  .github/workflows/tests.yml
Labels: 🐛 bug, Frontend squad

#3024 Fix Safari `TypeError: 'handleEvent'` iFrame resizer error
  app/views/component-preview.njk
  app/views/layouts/layout.njk
Labels: 🐛 bug, tech debt, Frontend squad

#2982 Migrate Gulp and Node.js build tasks to ESM
  config/paths.js
  docs/contributing/tasks.md
  gulpfile.mjs
  package-lock.json
  package.json
  postcss.config.js
  tasks/asset-version.mjs
  tasks/clean.mjs
  tasks/clean.unit.test.mjs
  tasks/gulp/__tests__/after-build-dist.test.mjs
  tasks/gulp/__tests__/after-build-package.test.mjs
  tasks/gulp/compile-assets.mjs
  tasks/gulp/copy-to-destination.mjs
  tasks/gulp/watch.mjs
  tasks/prototype-kit-config.mjs
  tasks/run.mjs
  tasks/task-arguments.js
  tasks/task-arguments.mjs
  tasks/task-arguments.unit.test.mjs
Labels: tooling, tech debt, Frontend squad

#3018 Allow Node.js LTS ‘Hydrogen’ (v18) release version
  .browserslistrc
  .nvmrc
  app/package.json
  docs/contributing/running-locally.md
  package-lock.json
  package.json
Labels: tooling, tech debt, Frontend squad

#3033 Ensure npm scripts (via Gulp) emit errors
  gulpfile.mjs
  tasks/run.mjs
Labels: tooling, Frontend squad

#3034 Allow Sass compilation to restart after `gulp dev` errors
  gulpfile.mjs
  package-lock.json
  package.json
  tasks/gulp/compile-assets.mjs
  tasks/task-arguments.mjs
Labels: sass / css, tooling, Frontend squad

#3035 Allow JavaScript compilation to restart after `gulp dev` errors
  gulpfile.mjs
  tasks/gulp/compile-assets.mjs
Labels: javascript, tooling, Frontend squad

#3023 Add source maps to compiled JavaScript + CSS
  tasks/asset-version.mjs
  tasks/gulp/__tests__/after-build-dist.test.mjs
  tasks/gulp/__tests__/after-build-package.test.mjs
  tasks/gulp/compile-assets.mjs
Labels: sass / css, javascript, tech debt, Frontend squad

#3045 Use native Fetch API in behaviour tests
  app/app.test.js
  app/banner.test.js
  app/full-page-examples.test.js
  app/package.json
  package-lock.json
Labels: tech debt, Frontend squad

#2848 Add Git hook to lint JavaScript and Sass file `pre-commit`
  .husky/pre-commit
  .lintstagedrc.js
  package-lock.json
  package.json
Labels: Frontend squad

#2984 Upgrade to `del` and `slash` "ESM only" packages
  jest.config.mjs
  package-lock.json
  package.json
  src/govuk/all.test.mjs
  tasks/clean.mjs
Labels: tooling, tech debt, Frontend squad

#3008 Add details of relevant docs parts to update when releasing
  docs/releasing/publishing.md
Labels: documentation, Frontend squad
