Repository alphagov/govuk-frontend, pull requests merged in 2022-09, with the labels that each got.

#2857 Make `config/paths.json` exportable for ESM import
  app/app.js
  app/app.test.js
  app/banner.test.js
  app/full-page-examples.test.js
  app/start.js
  config/paths.js
  config/paths.json
  gulpfile.js
  jest-puppeteer.config.js
  lib/file-helper.js
  lib/jest-helpers.js
  package-lock.json
  package.json
  src/govuk/all.test.js
  src/govuk/components/accordion/accordion.test.js
  src/govuk/components/all.test.js
  src/govuk/components/button/button.test.js
  src/govuk/components/character-count/character-count.test.js
  src/govuk/components/checkboxes/checkboxes.test.js
  src/govuk/components/details/details.test.js
  src/govuk/components/error-summary/error-summary.test.js
  src/govuk/components/header/header.test.js
  src/govuk/components/notification-banner/notification-banner.test.js
  src/govuk/components/radios/radios.test.js
  src/govuk/components/skip-link/skip-link.test.js
  src/govuk/components/tabs/tabs.test.js
  src/govuk/helpers/helpers.test.js
  src/govuk/objects/objects.test.js
  src/govuk/settings/colours.test.js
  src/govuk/settings/settings.test.js
  src/govuk/template.test.js
  src/govuk/tools/tools.test.js
  tasks/asset-version.js
  tasks/clean.js
  tasks/gulp/__tests__/after-build-dist.test.js
  tasks/gulp/__tests__/after-build-package.test.js
  tasks/gulp/__tests__/check-individual-components-compile.test.js
  tasks/gulp/compile-assets.js
  tasks/gulp/copy-to-destination.js
  tasks/gulp/watch.js
  tasks/nodemon.js
  tasks/sassdoc.js
Labels: javascript, javascript squad

#2858 Replace deprecated `request` package with Fetch API
  app/app.test.js
  app/banner.test.js
  app/full-page-examples.test.js
Labels: javascript, javascript squad

#2850 Improvements to Jest project setup + test package updates
  .github/workflows/tests.yml
  config/jest/browser/close.mjs
  config/jest/browser/open.mjs
  config/jest/matchers.js
  config/jest/server/start.mjs
  config/jest/server/stop.mjs
  docs/contributing/tasks.md
  jest-puppeteer.config.js
  jest.config.js
  package-lock.json
  package.json
  src/govuk/all.test.js
  src/govuk/components/accordion/accordion.test.js
  src/govuk/components/all.test.js
  src/govuk/components/button/button.test.js
  src/govuk/components/character-count/character-count.test.js
  src/govuk/components/checkboxes/checkboxes.test.js
  src/govuk/components/details/details.test.js
  src/govuk/components/error-summary/error-summary.test.js
  src/govuk/components/header/header.test.js
  src/govuk/components/notification-banner/notification-banner.test.js
  src/govuk/components/radios/radios.test.js
  src/govuk/components/skip-link/skip-link.test.js
  src/govuk/components/tabs/tabs.test.js
  tasks/gulp/__tests__/check-individual-components-compile.test.js
Labels: tooling, javascript squad

#2866 Fix 'Expected property shorthand' linter warning
  src/govuk/i18n.unit.test.mjs
Labels: javascript squad

#2865 Add JSDoc for accordion constructor
  src/govuk/components/accordion/accordion.mjs
Labels: javascript squad

#2870 Fix stray `let` in I18n preventing uglify (into `main`)
  .github/workflows/tests.yml
  lib/file-helper.js
  lib/jest-helpers.js
  package-lock.json
  package.json
  src/govuk/i18n.mjs
  tasks/gulp/copy-to-destination.js
Labels: tooling, javascript squad

#2862 Ensure all gulp tasks run to completion
  tasks/asset-version.js
  tasks/gulp/__tests__/after-build-package.test.js
  tasks/gulp/compile-assets.js
  tasks/gulp/copy-to-destination.js
  tasks/gulp/lint.js
  tasks/sassdoc.js
Labels: tooling, javascript squad

#2876 Don’t copy *.js files into `govuk-esm`
  gulpfile.js
  tasks/gulp/copy-to-destination.js
Labels: tooling, javascript squad

#2879 Fix missing assertion in header tests
  src/govuk/components/header/template.test.js
Labels: tooling, javascript squad

#2880 Fix Jest setup/teardown for test server awaiting `SIGTERM`
  config/jest/browser/open.mjs
  config/jest/server/start.mjs
  jest-puppeteer.config.js
  lib/jest-helpers.js
  src/govuk/components/button/button.test.js
  src/govuk/components/error-summary/error-summary.test.js
  src/govuk/components/notification-banner/notification-banner.test.js
Labels: tooling, javascript squad

#2863 Separate out CSS/JS lint tasks from `copy-assets`
  .gitattributes
  .github/workflows/tests.yml
  docs/contributing/coding-standards/css.md
  docs/contributing/tasks.md
  gulpfile.js
  package.json
  tasks/asset-version.js
  tasks/clean.js
  tasks/gulp/copy-to-destination.js
  tasks/gulp/lint.js
  tasks/gulp/watch.js
  tasks/nodemon.js
  tasks/run.js
  tasks/sassdoc.js
Labels: tooling, javascript squad

#2878 Reduce GitHub workflow runs (including Percy screenshot uploads)
  .github/workflows/sass.yaml
  .github/workflows/tests.yml
  config/jest/browser/open.mjs
  jest.config.js
  lib/.eslintrc.js
  lib/axe-helper.js
  lib/file-helper.js
  lib/jest-helpers.js
  lib/puppeteer-helpers.js
  src/govuk/components/all.test.js
  src/govuk/components/button/button.test.js
  src/govuk/components/character-count/character-count.test.js
  src/govuk/components/components.template.test.js
  src/govuk/components/components.test.js
  src/govuk/components/error-summary/error-summary.test.js
  src/govuk/components/notification-banner/notification-banner.test.js
  tasks/gulp/__tests__/after-build-dist.test.js
Labels: tooling, javascript squad

#2860 Add ESLint and Stylelint caches to GitHub actions workflow
  .github/workflows/tests.yml
  package-lock.json
  package.json
Labels: tooling, javascript squad
