Repository alphagov/govuk-frontend, pull requests merged in 2022-02, with the labels that each got.

#2527 Update changelog with 2i edits
  ...
  CHANGELOG.md
Labels: documentation, 🚀 release

#2536 Update release docs to move testing content and explain command output
  docs/contributing/testing.md
  docs/releasing/publishing-from-a-support-branch.md
  docs/releasing/publishing.md
Labels: documentation

#2546 Add example of type of input control
  src/govuk/components/input/input.yaml
Labels: documentation, 🕔 hours, text input, small story

#2551 Add Percy visual regression testing
  .github/workflows/tests.yml
  docs/releasing/testing-and-linting.md
  package-lock.json
  package.json
  src/govuk/components/all.test.js
Labels: tooling
