Repository alphagov/govuk-frontend, pull requests merged in 2022-12, with the labels that each got.

#3030 Test Ruby Sass on Ruby 3.1, Dart Sass on Node.js 18
  .github/workflows/sass.yaml
  .github/workflows/screenshots.yml
  .github/workflows/tests.yml
Labels: sass / css, dependencies, tech debt, Frontend squad

#3021 Printing style for current page link in header
  CHANGELOG.md
  src/govuk/components/header/_index.scss
Labels: header, sass / css, Design System squad

#3036 Bug: Percy uploads should complete before “finalizing”
  .github/workflows/screenshots.yml
Labels: 🐛 bug, 🔍 investigation, Frontend squad

#3078 Allow nodemon to continue after `npm run serve` errors
  tasks/run.mjs
Labels: tech debt, Frontend squad

#3094 Accordion margin/padding fixes
  src/govuk/components/accordion/_index.scss
  src/govuk/components/accordion/template.njk
Labels: sass / css, accordion

#3090 Add CHANGELOG entry for source maps
  CHANGELOG.md
Labels: sass / css, javascript, Frontend squad

#3105 Configure Heroku review app dyno size to “eco”
  app.json
Labels: Frontend squad

#3102 Ensure JSDoc blocks are complete
  babel.config.js
  config/jest/browser/open.mjs
  lib/file-helper.js
  lib/jest-helpers.js
  lib/puppeteer-helpers.js
  postcss.config.js
  src/govuk/common/index.mjs
  src/govuk/common/normalise-dataset.mjs
  src/govuk/components/accordion/accordion.mjs
  src/govuk/components/button/button.mjs
  src/govuk/components/button/button.test.js
  src/govuk/components/character-count/character-count.mjs
  src/govuk/components/checkboxes/checkboxes.mjs
  src/govuk/components/details/details.mjs
  src/govuk/components/error-summary/error-summary.mjs
  src/govuk/components/header/header.mjs
  src/govuk/components/notification-banner/notification-banner.mjs
  src/govuk/components/radios/radios.mjs
  src/govuk/components/skip-link/skip-link.mjs
  src/govuk/components/tabs/tabs.mjs
  src/govuk/i18n.mjs
  src/govuk/i18n.unit.test.mjs
  tasks/clean.mjs
  tasks/gulp/compile-assets.mjs
Labels: javascript, tech debt, Frontend squad

#3110 Rename `target` to `$target` and other tiny code style changes
  src/govuk/components/button/button.mjs
  src/govuk/components/checkboxes/checkboxes.mjs
  src/govuk/components/details/details.mjs
  src/govuk/components/error-summary/error-summary.mjs
  src/govuk/components/radios/radios.mjs
  src/govuk/components/tabs/tabs.mjs
Labels: javascript, tech debt, Frontend squad

#3113 Add version info from `package.json` to config
  app/app.test.js
  app/banner.test.js
  app/full-page-examples.test.js
  app/start.js
  config/index.js
  config/jest/server/start.mjs
  config/paths.js
  config/ports.js
  lib/puppeteer-helpers.js
  tasks/asset-version.mjs
  tasks/gulp/__tests__/after-build-dist.test.mjs
  tasks/gulp/compile-assets.mjs
Labels: tech debt, Frontend squad

#3114 Ensure `VERSION.txt` task accepts `--destination` flag
  gulpfile.mjs
  tasks/asset-version.mjs
  tasks/gulp/__tests__/after-build-dist.test.mjs
  tasks/task-arguments.mjs
Labels: tech debt, Frontend squad

#3088 Use standalone Rollup task (no Gulp)
  .github/dependabot.yml
  gulpfile.mjs
  lib/helper-functions.js
  lib/helper-functions.unit.test.js
  lib/helper-functions.unit.test.mjs
  lib/puppeteer-helpers.js
  package-lock.json
  package.json
  package.json.unit.test.js
  tasks/compile-javascripts.mjs
  tasks/gulp/__tests__/after-build-package.test.mjs
  tasks/gulp/compile-assets.mjs
Labels: tooling, tech debt, Frontend squad

#3127 Allow compile with lint errors in development
  .eslintrc.js
  gulpfile.mjs
Labels: tooling, tech debt, Frontend squad

#3075 Skip “Percy screenshots” when secrets are unavailable on forks (fix)
  .github/workflows/screenshots.yml
  .github/workflows/tests.yml
Labels: 🐛 bug, Frontend squad

#3132 Configure Dependabot for direct updates only
  .github/dependabot.yml
  package-lock.json
Labels: tooling, dependencies, Frontend squad

#3103 Configure ESLint to require JSDoc `@params` etc
  src/.eslintrc.js
  src/govuk/all.test.mjs
  src/govuk/components/accordion/accordion.test.js
  src/govuk/i18n.mjs
Labels: javascript, tech debt, Frontend squad

#3122 Accordion `$sections` should use `this.sectionClass` etc
  src/govuk/components/accordion/accordion.mjs
Labels: javascript, tech debt, Frontend squad

#3050 Run browser tests on minified code
  app/app.test.js
  app/views/examples/scoped-initialisation/index.njk
  app/views/examples/template-custom/index.njk
  app/views/examples/template-default/index.njk
  app/views/examples/translated/index.njk
  app/views/full-page-examples/campaign-page/index.njk
  app/views/full-page-examples/search/index.njk
  app/views/layouts/_generic.njk
  app/views/layouts/legacy.njk
  app/views/tests/boilerplate.njk
  docs/examples/webpack/index.html
  docs/examples/webpack/webpack.config.js
  tasks/compile-javascripts.mjs
  tasks/gulp/compile-assets.mjs
Labels: sass / css, javascript, Frontend squad
