Repository alphagov/govuk-frontend, pull requests merged in 2022-08, with the labels that each got.

#2672 Add static spacing override classes
  CHANGELOG.md
  src/govuk/overrides/_spacing.scss
Labels: awaiting triage

#2741 Remove prototype kit as a dependancy from release docs
  docs/releasing/publishing.md
Labels: documentation

#2759 Provide more details in our publishing docs
  docs/releasing/publishing.md
Labels: documentation

#2752 Change the Button component background and text colour
  CHANGELOG.md
  src/govuk/components/button/_index.scss
  tasks/sassdoc.js
Labels: feature request, button, javascript squad

#2720 Add parameter to localise mobile menu toggle button
  CHANGELOG.md
  src/govuk/components/header/header.yaml
  src/govuk/components/header/template.njk
  src/govuk/components/header/template.test.js
Labels: documentation, design, localisation, javascript squad, contribution squad, shared ownership

#2806 fix(code-quality): Variable conflict & typing error rectification
  tasks/gulp/compile-assets.js
Labels: tooling, tech debt

#2807 Tidy up and refactor the Character Count JavaScript
  CHANGELOG.md
  src/govuk/components/character-count/character-count.mjs
Labels: javascript squad
