Repository alphagov/govuk-frontend, pull requests merged in 2023-10, with the labels that each got.

#4268 Allow border and hover colours to be overridden
  CHANGELOG.md
  packages/govuk-frontend/src/govuk/settings/_colours-applied.scss
Labels: submitted by user, sass / css

#4306 Log formatted warnings from Rollup
  shared/tasks/scripts.mjs
Labels: javascript, tooling

#4326 Fix empty spaces `" >` on opening tags
  packages/govuk-frontend-review/src/views/examples/typography/index.njk
  packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/notification-banner/template.njk
Labels: 🐛 bug

#4324 Ignore tests in watch tasks
  packages/govuk-frontend-review/tasks/watch.mjs
  packages/govuk-frontend/tasks/watch.mjs
Labels: tooling

#4320 Move `getFragmentFromUrl()` to common utilities
  packages/govuk-frontend/src/govuk/common/index.jsdom.test.mjs
  packages/govuk-frontend/src/govuk/common/index.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
Labels: skip link, javascript, error summary, tabs

#4322 Reduce file size using `for...of` loops + other optimisations
  packages/govuk-frontend/src/govuk/common/index.jsdom.test.mjs
  packages/govuk-frontend/src/govuk/common/index.mjs
  packages/govuk-frontend/src/govuk/common/normalise-dataset.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
  packages/govuk-frontend/src/govuk/components/button/button.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
  packages/govuk-frontend/src/govuk/i18n.mjs
Labels: javascript

#4321 Assert Exit this page `HTMLAnchorElement` button and clearly guard all dynamic fields
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
Labels: javascript, exit this page

#4330 Support `beforeInitialisation()` options, multiple modules
  packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
  shared/helpers/puppeteer.js
Labels: assurance, tooling

#4349 Refactor ElementError
  packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/button/button.mjs
  packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/header/header.mjs
  packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/radios/radios.mjs
  packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
  packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
  packages/govuk-frontend/src/govuk/errors/index.mjs
Labels: javascript

#4325 Review types used in `instanceof` checks
  package-lock.json
  package.json
  packages/govuk-frontend-review/tsconfig.build.json
  packages/govuk-frontend-review/tsconfig.dev.json
  packages/govuk-frontend/src/govuk/all.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
  packages/govuk-frontend/src/govuk/components/header/header.mjs
  packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/radios/radios.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
  packages/govuk-frontend/tsconfig.build.json
  packages/govuk-frontend/tsconfig.dev.json
  shared/helpers/tsconfig.json
  shared/tasks/tsconfig.json
Labels: assurance

#4327 Fix Nunjucks `default()` values when `null`, `false` or `""` is provided
  CHANGELOG.md
  packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
  packages/govuk-frontend/src/govuk/components/cookie-banner/template.njk
  packages/govuk-frontend/src/govuk/components/exit-this-page/template.njk
  packages/govuk-frontend/src/govuk/components/footer/template.njk
  packages/govuk-frontend/src/govuk/components/header/template.njk
  packages/govuk-frontend/src/govuk/components/input/template.njk
  packages/govuk-frontend/src/govuk/components/notification-banner/template.njk
  packages/govuk-frontend/src/govuk/components/pagination/template.njk
  packages/govuk-frontend/src/govuk/components/radios/template.njk
  packages/govuk-frontend/src/govuk/components/select/template.njk
  packages/govuk-frontend/src/govuk/components/skip-link/template.njk
  packages/govuk-frontend/src/govuk/components/warning-text/template.njk
  packages/govuk-frontend/src/govuk/template.njk
Labels: 🐛 bug, nunjucks

#4329 Add lib functions `renderTemplate()` and `renderPreview()` etc
  package-lock.json
  packages/govuk-frontend-review/src/app.mjs
  packages/govuk-frontend-review/src/common/middleware/assets.mjs
  packages/govuk-frontend-review/src/common/nunjucks/globals/get-html-code.mjs
  packages/govuk-frontend-review/src/common/nunjucks/globals/get-nunjucks-code.mjs
  packages/govuk-frontend-review/src/views/macros/showExamples.njk
  packages/govuk-frontend-review/src/views/tests/boilerplate.njk
  packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/character-count/character-count.jsdom.test.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/components.template.test.js
  packages/govuk-frontend/src/govuk/components/details/template.test.js
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/error-summary/template.test.js
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/fieldset/template.test.js
  packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/inset-text/template.test.js
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/notification-banner/template.test.js
  packages/govuk-frontend/src/govuk/components/panel/template.test.js
  packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
  packages/govuk-frontend/src/govuk/macros/i18n.unit.test.mjs
  packages/govuk-frontend/src/govuk/template.test.js
  shared/helpers/nunjucks.js
  shared/helpers/puppeteer.js
  shared/lib/components.js
  shared/lib/package.json
  shared/tasks/components.mjs
Labels: nunjucks, tooling

#4370 Base pre-release documentation on release documentation
  docs/releasing/publishing-a-pre-release.md
  docs/releasing/publishing.md
Labels: documentation

#4323 Review and guard all missing fields/attributes
  docs/contributing/coding-standards/js.md
  packages/govuk-frontend/src/govuk/common/index.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
  packages/govuk-frontend/src/govuk/components/button/button.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
  packages/govuk-frontend/src/govuk/components/header/header.mjs
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
  packages/govuk-frontend/src/govuk/components/radios/radios.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
  packages/govuk-frontend/src/govuk/errors/index.mjs
  packages/govuk-frontend/src/govuk/i18n.mjs
Labels: javascript

#4375 Add optional `.gitignore` files to package:clean task
  packages/govuk-frontend/package.json
Labels: 🐛 bug, assurance

#4378 Fix publish script `package.json` version etc
  bin/build-release.sh
  bin/generate-npm-tag.sh
  bin/publish-release.sh
Labels: 🐛 bug

#4391 Move private workspace packages to `devDependencies`
  package-lock.json
  packages/govuk-frontend/package.json
Labels: 🐛 bug, submitted by user

#4395 Update browser-support.md to remove table format
  docs/contributing/browser-support.md
Labels: documentation

#4394 Improve SupportError when `document.body` is not set
  packages/govuk-frontend/src/govuk/common/index.jsdom.test.mjs
  packages/govuk-frontend/src/govuk/common/index.mjs
  packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
  packages/govuk-frontend/src/govuk/errors/index.mjs
Labels: 🐛 bug, javascript

#4201 Allow Node.js LTS ‘Iron’ (v20) release version
  .browserslistrc
  .github/workflows/actions/setup-node/action.yml
  .github/workflows/sass.yaml
  .github/workflows/scripts/package.json
  .nvmrc
  docs/examples/webpack/.browserslistrc
  package-lock.json
  package.json
  packages/govuk-frontend-review/.browserslistrc
  packages/govuk-frontend-review/package.json
  packages/govuk-frontend/.browserslistrc
  shared/config/package.json
  shared/helpers/package.json
  shared/lib/package.json
  shared/stats/package.json
  shared/tasks/package.json
Labels: tooling, github_actions

#4408 Fix Dependabot by removing npm `engine-strict=true`
  .npmrc
Labels: dependencies, github_actions
