Repository alphagov/govuk-frontend, pull requests merged in 2023-08, with the labels that each got.

#3956 Add GitHub Actions export tests for Node.js v20
  .github/workflows/tests.yml
Labels: github_actions

#3919 Clarify docs for all nested options
  packages/govuk-frontend/src/govuk/components/accordion/accordion.yaml
  packages/govuk-frontend/src/govuk/components/summary-list/summary-list.yaml
Labels: documentation

#4044 Update testing and linting documentation
  docs/contributing/coding-standards/css.md
  docs/contributing/coding-standards/js.md
  docs/releasing/testing-and-linting.md
Labels: documentation

#3799 Format Sass stylesheets using Prettier
  .lintstagedrc.js
  .prettierrc.js
  docs/contributing/coding-standards/css.md
  package-lock.json
  package.json
  packages/govuk-frontend-review/src/stylesheets/full-page-examples/campaign-page.scss
  packages/govuk-frontend/src/govuk/components/accordion/_index.scss
  packages/govuk-frontend/src/govuk/components/back-link/_index.scss
  packages/govuk-frontend/src/govuk/components/breadcrumbs/_index.scss
  packages/govuk-frontend/src/govuk/components/button/_index.scss
  packages/govuk-frontend/src/govuk/components/checkboxes/_index.scss
  packages/govuk-frontend/src/govuk/components/cookie-banner/_index.scss
  packages/govuk-frontend/src/govuk/components/details/_index.scss
  packages/govuk-frontend/src/govuk/components/exit-this-page/_index.scss
  packages/govuk-frontend/src/govuk/components/fieldset/_index.scss
  packages/govuk-frontend/src/govuk/components/file-upload/_index.scss
  packages/govuk-frontend/src/govuk/components/footer/_index.scss
  packages/govuk-frontend/src/govuk/components/header/_index.scss
  packages/govuk-frontend/src/govuk/components/hint/_index.scss
  packages/govuk-frontend/src/govuk/components/input/_index.scss
  packages/govuk-frontend/src/govuk/components/radios/_index.scss
  packages/govuk-frontend/src/govuk/components/select/_index.scss
  packages/govuk-frontend/src/govuk/components/tabs/_index.scss
  packages/govuk-frontend/src/govuk/components/textarea/_index.scss
  packages/govuk-frontend/src/govuk/core/_global-styles.scss
  packages/govuk-frontend/src/govuk/core/_links.scss
  packages/govuk-frontend/src/govuk/core/_lists.scss
  packages/govuk-frontend/src/govuk/core/_section-break.scss
  packages/govuk-frontend/src/govuk/core/_typography.scss
  packages/govuk-frontend/src/govuk/helpers/_device-pixels.scss
  packages/govuk-frontend/src/govuk/helpers/_focused.scss
  packages/govuk-frontend/src/govuk/helpers/_links.scss
  packages/govuk-frontend/src/govuk/helpers/_spacing.scss
  packages/govuk-frontend/src/govuk/helpers/_typography.scss
  packages/govuk-frontend/src/govuk/objects/_grid.scss
  packages/govuk-frontend/src/govuk/objects/_template.scss
  packages/govuk-frontend/src/govuk/objects/_width-container.scss
  packages/govuk-frontend/src/govuk/overrides/_spacing.scss
  packages/govuk-frontend/src/govuk/settings/_colours-organisations.scss
  packages/govuk-frontend/src/govuk/settings/_colours-palette.scss
  packages/govuk-frontend/src/govuk/settings/_links.scss
  packages/govuk-frontend/src/govuk/settings/_measurements.scss
  packages/govuk-frontend/src/govuk/settings/_media-queries.scss
  packages/govuk-frontend/src/govuk/settings/_warnings.scss
  packages/govuk-frontend/src/govuk/tools/_font-url.scss
  packages/govuk-frontend/src/govuk/tools/_image-url.scss
  stylelint.config.js
Labels: sass / css, assurance, tooling

#4069 Update TypeScript paths to minimise included files
  .github/workflows/scripts/tsconfig.json
  packages/govuk-frontend-review/src/common/nunjucks/globals/get-html-code.mjs
  packages/govuk-frontend-review/tsconfig.build.json
  packages/govuk-frontend-review/tsconfig.json
  packages/govuk-frontend/tsconfig.build.json
  packages/govuk-frontend/tsconfig.json
  shared/config/tsconfig.json
  shared/helpers/tsconfig.json
  shared/lib/tsconfig.json
  shared/stats/tsconfig.json
  shared/tasks/tsconfig.json
  tsconfig.base.json
  tsconfig.json
Labels: javascript, tooling

#3958 Configure Babel to remove non-public comments
  .eslintrc.js
  docs/contributing/coding-standards/js.md
  packages/govuk-frontend/babel.config.js
  packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
  packages/govuk-frontend/src/govuk/components/button/button.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
  packages/govuk-frontend/src/govuk/components/header/header.mjs
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
  packages/govuk-frontend/src/govuk/components/radios/radios.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
Labels: javascript

#4089 Add type discovery to `src` symlink directories
  src/tsconfig.json
Labels: javascript, tooling

#4097 Fix missing `&&` in lint script
  package.json
Labels: 🐛 bug

#4101 Add metadata to Prototype Kit plugin config
  package-lock.json
  packages/govuk-frontend/package.json
  packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
  packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs
Labels: interoperability, prototype kit

#4151 Fix missing full stops in macro option descriptions
  packages/govuk-frontend/src/govuk/components/button/button.yaml
  packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.yaml
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.yaml
  packages/govuk-frontend/src/govuk/components/fieldset/fieldset.yaml
  packages/govuk-frontend/src/govuk/components/header/header.yaml
  packages/govuk-frontend/src/govuk/components/radios/radios.yaml
  packages/govuk-frontend/src/govuk/components/table/table.yaml
  packages/govuk-frontend/src/govuk/components/tabs/tabs.yaml
  packages/govuk-frontend/src/govuk/components/warning-text/warning-text.yaml
Labels: 🐛 bug, documentation
