Repository alphagov/govuk-frontend, pull requests merged in 2023-06, with the labels that each got.

#3727 Add shared `getComponentNames()` and other lib functions
  package-lock.json
  packages/govuk-frontend-review/package.json
  packages/govuk-frontend-review/src/app.mjs
  packages/govuk-frontend-review/src/app.test.mjs
  packages/govuk-frontend-review/src/common/lib/files.mjs
  packages/govuk-frontend-review/src/common/lib/files.test.mjs
  packages/govuk-frontend-review/src/routes/full-page-examples.mjs
  packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
  packages/govuk-frontend/src/govuk/components/components.template.test.js
  packages/govuk-frontend/tasks/build/package.test.mjs
  shared/lib/files.js
  shared/lib/files.unit.test.js
  shared/lib/package.json
  shared/tasks/browser.mjs
Labels: tooling

#3730 Split Rollup plugins into input and output etc
  docs/contributing/coding-standards/js.md
  docs/contributing/tasks.md
  packages/govuk-frontend-review/nodemon.json
  packages/govuk-frontend-review/rollup.config.mjs
  packages/govuk-frontend-review/tsconfig.json
  packages/govuk-frontend/.eslintrc.js
  packages/govuk-frontend/rollup.esm.config.mjs
  packages/govuk-frontend/rollup.release.config.mjs
  packages/govuk-frontend/tasks/build/package.test.mjs
  packages/govuk-frontend/tasks/scripts.mjs
  shared/lib/names.js
  shared/tasks/scripts.mjs
  tsconfig.base.json
Labels: documentation, javascript, tooling

#3731 Remove the first letter modifier from the tag component
  CHANGELOG.md
  packages/govuk-frontend/src/govuk/components/tag/_index.scss
Labels: sass / css, tag

#3732 Update references from back link to inset text in inset text options list
  packages/govuk-frontend/src/govuk/components/inset-text/inset-text.yaml
Labels: documentation, submitted by user, inset text

#3760 Use pinned `puppeteer-core` Chrome browser version
  package-lock.json
  shared/helpers/jest/browser/download.mjs
  shared/helpers/jest/browser/download.test.mjs
  shared/helpers/package.json
Labels: 🐛 bug, assurance

#3698 Enable ESLint + Stylelint for code inside Markdown
  .eslintrc.js
  .lintstagedrc.js
  CHANGELOG.md
  docs/contributing/coding-standards/css.md
  docs/contributing/coding-standards/js.md
  docs/contributing/coding-standards/nunjucks-api.md
  docs/contributing/managing-change.md
  docs/contributing/running-locally.md
  docs/contributing/testing.md
  docs/releasing/publishing-from-a-support-branch.md
  docs/releasing/publishing.md
  docs/releasing/testing-and-linting.md
  jest.config.mjs
  package-lock.json
  package.json
  packages/govuk-frontend-review/tasks/watch.mjs
  packages/govuk-frontend/src/govuk/components/details/implementation.md
  packages/govuk-frontend/tasks/watch.mjs
  stylelint.config.js
Labels: assurance, tooling

#3769 Migrate to use `<script type="module">`
  docs/examples/webpack/.gitignore
  docs/examples/webpack/src/index.html
  docs/examples/webpack/webpack.config.js
  packages/govuk-frontend-review/rollup.config.mjs
  packages/govuk-frontend-review/src/views/component-preview.njk
  packages/govuk-frontend-review/src/views/examples/scoped-initialisation/index.njk
  packages/govuk-frontend-review/src/views/examples/template-custom/index.njk
  packages/govuk-frontend-review/src/views/examples/template-default/index.njk
  packages/govuk-frontend-review/src/views/examples/translated/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-client-side/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-essential-cookies/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-server-side/index.njk
  packages/govuk-frontend-review/src/views/layouts/_generic.njk
  packages/govuk-frontend-review/src/views/layouts/layout.njk
  packages/govuk-frontend-review/src/views/tests/boilerplate.njk
  packages/govuk-frontend/README.md
  packages/govuk-frontend/rollup.release.config.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
  packages/govuk-frontend/src/govuk/components/radios/radios.mjs
Labels: documentation, javascript

#3770 Upgrade ESLint configuration for ES2015 (without classes)
  .eslintrc.js
  docs/contributing/coding-standards/js.md
  packages/govuk-frontend-review/src/views/examples/scoped-initialisation/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-client-side/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-essential-cookies/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-server-side/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/passport-details/index.mjs
  packages/govuk-frontend/.eslintrc.js
  packages/govuk-frontend/src/govuk/all.mjs
  packages/govuk-frontend/src/govuk/common/closest-attribute-value.mjs
  packages/govuk-frontend/src/govuk/common/govuk-frontend-version.mjs
  packages/govuk-frontend/src/govuk/common/index.mjs
  packages/govuk-frontend/src/govuk/common/normalise-dataset.mjs
  packages/govuk-frontend/src/govuk/common/normalise-dataset.unit.test.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accordion.test.js
  packages/govuk-frontend/src/govuk/components/button/button.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/template.test.js
  packages/govuk-frontend/src/govuk/components/date-input/template.test.js
  packages/govuk-frontend/src/govuk/components/details/details.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
  packages/govuk-frontend/src/govuk/components/file-upload/template.test.js
  packages/govuk-frontend/src/govuk/components/header/header.mjs
  packages/govuk-frontend/src/govuk/components/input/template.test.js
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
  packages/govuk-frontend/src/govuk/components/radios/radios.mjs
  packages/govuk-frontend/src/govuk/components/radios/template.test.js
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
  packages/govuk-frontend/src/govuk/components/textarea/template.test.js
  packages/govuk-frontend/src/govuk/i18n.mjs
  packages/govuk-frontend/src/govuk/template.test.js
  packages/govuk-frontend/tasks/build/package.test.mjs
  packages/govuk-frontend/tasks/build/release.test.mjs
  shared/tasks/files.mjs
Labels: javascript, tooling

#3756 Allow globs in paths for `getListing()` and `getDirectories()`
  packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
  packages/govuk-frontend/src/govuk/components/components.test.js
  packages/govuk-frontend/src/govuk/helpers/helpers.test.js
  packages/govuk-frontend/src/govuk/objects/objects.test.js
  packages/govuk-frontend/src/govuk/settings/settings.test.js
  packages/govuk-frontend/src/govuk/tools/tools.test.js
  packages/govuk-frontend/tasks/build/package.test.mjs
  packages/govuk-frontend/tasks/build/release.test.mjs
  shared/lib/files.js
  shared/tasks/components.mjs
  shared/tasks/scripts.mjs
  shared/tasks/styles.mjs
Labels: interoperability, tooling

#3767 Wait for Percy to idle before screenshot task finishes
  package-lock.json
  packages/govuk-frontend-review/percy.config.js
  shared/tasks/browser.mjs
  shared/tasks/package.json
Labels: 🐛 bug, assurance

#3757 Update package helpers to support `govuk-frontend@4`
  packages/govuk-frontend-review/browsersync.config.js
  packages/govuk-frontend-review/nodemon.json
  packages/govuk-frontend-review/rollup.config.mjs
  packages/govuk-frontend-review/src/common/middleware/assets.mjs
  packages/govuk-frontend-review/src/common/middleware/vendor.mjs
  packages/govuk-frontend-review/src/common/nunjucks/globals/get-html-code.mjs
  packages/govuk-frontend-review/src/common/nunjucks/index.mjs
  packages/govuk-frontend-review/typedoc.config.js
  packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
  shared/helpers/nunjucks.js
  shared/lib/files.js
  shared/lib/names.js
  shared/lib/names.unit.test.mjs
  shared/stats/rollup.config.mjs
  shared/stats/src/index.mjs
  shared/tasks/styles.mjs
Labels: interoperability, tooling

#3771 Migrate JavaScript to ES2015 classes
  docs/contributing/coding-standards/js.md
  packages/govuk-frontend/.eslintrc.js
  packages/govuk-frontend/src/govuk/all.mjs
  packages/govuk-frontend/src/govuk/common/closest-attribute-value.mjs
  packages/govuk-frontend/src/govuk/common/index.mjs
  packages/govuk-frontend/src/govuk/common/normalise-dataset.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
  packages/govuk-frontend/src/govuk/components/button/button.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.unit.test.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
  packages/govuk-frontend/src/govuk/components/details/details.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
  packages/govuk-frontend/src/govuk/components/header/header.mjs
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
  packages/govuk-frontend/src/govuk/components/radios/radios.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
  packages/govuk-frontend/src/govuk/i18n.mjs
  packages/govuk-frontend/tasks/build/package.test.mjs
Labels: javascript

#3807 Fix flaky tests with debounce timeouts
  packages/govuk-frontend/src/govuk/components/button/button.test.js
  packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js
Labels: button, assurance, character count

#3801 Add class `.govuk-frontend-supported` for ES modules support
  docs/contributing/coding-standards/js.md
  docs/examples/webpack/src/index.html
  packages/govuk-frontend-review/src/views/tests/boilerplate.njk
  packages/govuk-frontend/src/govuk/all.mjs
  packages/govuk-frontend/src/govuk/components/accordion/_index.scss
  packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
  packages/govuk-frontend/src/govuk/components/button/button.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.unit.test.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/_index.scss
  packages/govuk-frontend/src/govuk/components/details/details.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
  packages/govuk-frontend/src/govuk/components/header/_index.scss
  packages/govuk-frontend/src/govuk/components/header/header.mjs
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
  packages/govuk-frontend/src/govuk/components/radios/_index.scss
  packages/govuk-frontend/src/govuk/components/radios/radios.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
  packages/govuk-frontend/src/govuk/components/tabs/_index.scss
  packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
  packages/govuk-frontend/src/govuk/template.njk
  packages/govuk-frontend/src/govuk/template.test.js
Labels: sass / css, javascript

#3811 Remove Prettier warning for GOV.UK Prototype Kit config
  .prettierignore
  .prettierrc.js
Labels: 🐛 bug

#3810 Remove TypeDoc export warning for private `I18n`
  packages/govuk-frontend-review/typedoc.config.js
Labels: 🐛 bug

#3809 Use Prettier for Nunjucks preview formatting
  package-lock.json
  packages/govuk-frontend-review/package.json
  packages/govuk-frontend-review/src/common/nunjucks/globals/get-nunjucks-code.mjs
Labels: design, interoperability

#3833 Migrate to `import { initAll }` from ES module bundle
  babel.config.js
  package-lock.json
  packages/govuk-frontend-review/rollup.config.mjs
  packages/govuk-frontend-review/src/app.mjs
  packages/govuk-frontend-review/src/javascripts/all.mjs
  packages/govuk-frontend-review/src/views/component-preview.njk
  packages/govuk-frontend-review/src/views/examples/scoped-initialisation/index.njk
  packages/govuk-frontend-review/src/views/examples/template-custom/index.njk
  packages/govuk-frontend-review/src/views/examples/template-default/index.njk
  packages/govuk-frontend-review/src/views/examples/translated/index.njk
  packages/govuk-frontend-review/src/views/layouts/_generic.njk
  packages/govuk-frontend-review/src/views/tests/boilerplate.njk
  packages/govuk-frontend-review/tasks/scripts.mjs
  packages/govuk-frontend/postcss.config.mjs
  packages/govuk-frontend/src/govuk/components/button/button.test.js
  packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.test.js
  packages/govuk-frontend/src/govuk/components/globals.test.mjs
  shared/helpers/package.json
  shared/helpers/puppeteer.js
  shared/helpers/tsconfig.json
  shared/tasks/helpers/task-arguments.js
  shared/tasks/helpers/task-arguments.unit.test.js
  shared/tasks/npm.mjs
Labels: documentation, javascript

#3863 Fix helpers `getListing()` and `getDirectories()` on Windows etc
  .github/workflows/actions/build/action.yml
  .github/workflows/actions/install-node/action.yml
  .github/workflows/screenshots.yml
  .github/workflows/tests.yml
  jest-dev-server.config.js
  jest.config.mjs
  package-lock.json
  packages/govuk-frontend/src/govuk/components/accordion/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accordion.test.js
  packages/govuk-frontend/src/govuk/components/back-link/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/breadcrumbs/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/button/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/button/button.test.js
  packages/govuk-frontend/src/govuk/components/character-count/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js
  packages/govuk-frontend/src/govuk/components/checkboxes/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/cookie-banner/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/date-input/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/details/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/error-message/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/fieldset/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/file-upload/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/footer/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/header/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/hint/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/input/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/inset-text/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/label/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/notification-banner/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/pagination/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/panel/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/phase-banner/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/radios/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/select/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/summary-list/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/table/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/tabs/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.test.js
  packages/govuk-frontend/src/govuk/components/tag/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/textarea/accessibility.test.mjs
  packages/govuk-frontend/src/govuk/components/warning-text/accessibility.test.mjs
  packages/govuk-frontend/tasks/build/release.test.mjs
  shared/lib/files.js
  shared/lib/package.json
  shared/tasks/files.mjs
Labels: 🐛 bug, github-actions

#3836 Announce whitespace in screen reader announcements of visually hidden text
  app/src/views/examples/typography/index.njk
  src/govuk/helpers/_visually-hidden.scss
Labels: accessibility, submitted by user

#3872 Add class `.govuk-frontend-supported` for ES modules support (Checkboxes)
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
Labels: 🐛 bug

#3867 Simplify i18n macro to handle single or plural text
  packages/govuk-frontend/src/govuk/components/accordion/template.njk
  packages/govuk-frontend/src/govuk/components/character-count/template.njk
  packages/govuk-frontend/src/govuk/macros/i18n.njk
  packages/govuk-frontend/src/govuk/macros/i18n.unit.test.mjs
  shared/helpers/nunjucks.js
Labels: assurance

#3869 Fix component data typos, missing fields etc
  packages/govuk-frontend/gulpfile.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
  packages/govuk-frontend/src/govuk/components/radios/radios.yaml
  packages/govuk-frontend/src/govuk/components/summary-list/summary-list.yaml
  packages/govuk-frontend/src/govuk/components/tabs/tabs.yaml
  packages/govuk-frontend/src/govuk/components/task-list/task-list.yaml
  packages/govuk-frontend/tasks/watch.mjs
  shared/lib/files.js
Labels: 🐛 bug
