Repository alphagov/govuk-frontend, pull requests merged in 2023-09, with the labels that each got.

#4158 Remove unused `assetsPath` for IE8 fallback GOV.UK logo
  packages/govuk-frontend/src/govuk/components/header/header.yaml
Labels: documentation

#4170 Remove incorrect `params.text` Button description etc
  packages/govuk-frontend/src/govuk/components/button/button.yaml
Labels: 🐛 bug, documentation

#4177 Add MissingElementError and use it within the Skip Link
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.test.js
  packages/govuk-frontend/src/govuk/errors/index.mjs
Labels: skip link, javascript

#4183 Update character count types to show `maxlength` can be ignored
  packages/govuk-frontend/src/govuk/all.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
Labels: assurance, character count, interoperability

#4182 Remove stray `.only()` from PR #4030
  packages/govuk-frontend/src/govuk/common/index.unit.test.mjs
Labels: 🐛 bug

#4184 Configure ESLint for required JSDoc `@param` descriptions
  .eslintrc.js
  packages/govuk-frontend/.eslintrc.js
Labels: assurance, interoperability

#4176 Throw `ConfigError` when component configs are invalid
  packages/govuk-frontend-review/typedoc.config.js
  packages/govuk-frontend/.eslintrc.js
  packages/govuk-frontend/src/govuk/all.mjs
  packages/govuk-frontend/src/govuk/common/index.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js
  packages/govuk-frontend/src/govuk/components/character-count/character-count.unit.test.mjs
  packages/govuk-frontend/src/govuk/errors/index.mjs
  shared/helpers/puppeteer.js
Labels: javascript, character count

#4187 Remove export warning for `Schema` from TypeDoc
  packages/govuk-frontend-review/typedoc.config.js
Labels: 🐛 bug

#4204 Use absolute Rollup input paths to fix `Unexpected token`
  shared/stats/rollup.config.mjs
Labels: 🐛 bug, dependencies

#4208 Always run Rollup build for `all.mjs` last
  packages/govuk-frontend/tasks/scripts.mjs
  shared/tasks/scripts.mjs
  shared/tasks/styles.mjs
Labels: 🐛 bug

#4200 Fix missing update for `actions/setup-node@v3.8.1`
  .github/workflows/actions/setup-node/action.yml
Labels: 🐛 bug

#4239 Fix Review app Sass compile after error
  shared/tasks/npm.mjs
  shared/tasks/scripts.mjs
  shared/tasks/styles.mjs
Labels: 🐛 bug, sass / css

#4260 Fix double redirect to HTML specification
  packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
  packages/govuk-frontend/src/govuk/components/footer/footer.yaml
  packages/govuk-frontend/src/govuk/components/input/input.yaml
Labels: documentation

#4092 Use new “Open this example in a new tab” link text
  package-lock.json
  packages/govuk-frontend-review/package.json
  packages/govuk-frontend-review/src/common/nunjucks/filters/index.mjs
  packages/govuk-frontend-review/src/common/nunjucks/filters/markdown.mjs
  packages/govuk-frontend-review/src/common/nunjucks/globals/index.mjs
  packages/govuk-frontend-review/src/common/nunjucks/globals/markdown.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/bank-holidays/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/campaign-page/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/check-your-answers/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/child-maintenance/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-client-side/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-essential-cookies/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-server-side/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/feedback/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/have-you-changed-your-name/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/how-do-you-want-to-sign-in/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/passport-details/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/search/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/service-manual-topic/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/start-page/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/task-list/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/update-your-account-details/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo-success/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-address/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-nationality/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-postcode/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/what-was-the-last-country-you-visited/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/work-history/index.njk
  packages/govuk-frontend-review/src/views/macros/showExamples.njk
Labels: design, consistency

#4245 Increase Jest + Puppeteer timeouts for Windows
  jest-dev-server.config.js
  jest.config.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/back-link/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/breadcrumbs/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/button/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/character-count/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/cookie-banner/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/date-input/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/details/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/error-message/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/exit-this-page/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/fieldset/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/file-upload/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/footer/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/header/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/hint/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/input/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/inset-text/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/label/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/notification-banner/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/pagination/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/panel/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/phase-banner/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/radios/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/select/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/summary-list/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/table/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/tabs/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/tag/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/textarea/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/warning-text/accessibility.puppeteer.test.mjs
Labels: assurance, github_actions

#4240 Add new `govuk-frontend.min.css` package bundle
  CHANGELOG.md
  docs/contributing/tasks.md
  packages/govuk-frontend-review/tasks/watch.mjs
  packages/govuk-frontend/tasks/build/package.unit.test.mjs
  packages/govuk-frontend/tasks/build/release.mjs
  packages/govuk-frontend/tasks/styles.mjs
Labels: sass / css

#4241 Skip JSDoc, SassDoc, Rollup stats during dev, add ESLint
  .github/workflows/actions/build/action.yml
  .github/workflows/tests.yml
  docs/contributing/tasks.md
  docs/examples/webpack/package.json
  jest.config.mjs
  package-lock.json
  package.json
  packages/govuk-frontend-review/gulpfile.mjs
  packages/govuk-frontend-review/nodemon.json
  packages/govuk-frontend-review/package.json
  packages/govuk-frontend-review/src/app.mjs
  packages/govuk-frontend-review/src/views/index.njk
  packages/govuk-frontend-review/tasks/build/dist.mjs
  packages/govuk-frontend-review/tasks/index.mjs
  packages/govuk-frontend-review/tasks/scripts.mjs
  packages/govuk-frontend-review/tasks/styles.mjs
  packages/govuk-frontend-review/tasks/watch.mjs
  packages/govuk-frontend/package.json
  packages/govuk-frontend/tasks/build/package.mjs
  packages/govuk-frontend/tasks/build/release.mjs
  packages/govuk-frontend/tasks/scripts.mjs
  packages/govuk-frontend/tasks/watch.mjs
  shared/lib/files.js
  shared/stats/package.json
  shared/tasks/files.mjs
  shared/tasks/npm.mjs
  shared/tasks/package.json
Labels: tooling
