Repository alphagov/govuk-frontend, pull requests merged in 2023-03, with the labels that each got.

#3164 Migrate GOV.UK Frontend build pipeline to use Dart Sass
  docs/contributing/running-locally.md
  docs/examples/webpack/package.json
  lib/jest-helpers.js
  package-lock.json
  package.json
  src/govuk/all.test.mjs
  src/govuk/components/components.test.js
  src/govuk/helpers/colour.test.js
  src/govuk/helpers/grid.test.js
  src/govuk/helpers/helpers.test.js
  src/govuk/helpers/spacing.test.js
  src/govuk/helpers/typography.test.js
  src/govuk/objects/objects.test.js
  src/govuk/objects/width-container.test.js
  src/govuk/settings/settings.test.js
  src/govuk/settings/warnings.test.js
  src/govuk/tools/compatibility.test.js
  src/govuk/tools/font-url.test.js
  src/govuk/tools/ie8.test.js
  src/govuk/tools/image-url.test.js
  src/govuk/tools/tools.test.js
  tasks/compile-stylesheets.mjs
Labels: sass / css, interoperability, tooling, dependencies

#3344 Adding optional id attribute to button component
  CHANGELOG.md
  src/govuk/components/button/button.yaml
  src/govuk/components/button/template.njk
  src/govuk/components/button/template.test.js
Labels: feature request, button, nunjucks

#2230 Add extra letter spacing modifier for inputs
  CHANGELOG.md
  src/govuk/components/input/_index.scss
  src/govuk/components/input/input.yaml
Labels: text input

#3373 Ensure Nunjucks global `markdown()` renders correctly
  app/app.test.js
  app/common/nunjucks/globals/index.js
Labels: 🐛 bug

#3370 Build tasks: Clearly show subdirectory paths
  app/src/app.mjs
  app/src/app.test.mjs
  app/src/common/middleware/assets.mjs
  app/src/common/middleware/docs.mjs
  app/src/common/nunjucks/globals/get-html-code.mjs
  app/src/common/nunjucks/index.mjs
  config/jest/globals.mjs
  config/paths.js
  lib/file-helper.js
  lib/helper-functions.unit.test.mjs
  lib/jest-helpers.js
  src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
  src/govuk/all.test.mjs
  src/govuk/components/components.template.test.js
  src/govuk/components/components.test.js
  src/govuk/helpers/helpers.test.js
  src/govuk/objects/objects.test.js
  src/govuk/settings/settings.test.js
  src/govuk/template.test.js
  src/govuk/tools/tools.test.js
  src/tsconfig.json
  tasks/compile-stylesheets.mjs
  tasks/gulp/__tests__/after-build-dist.test.mjs
  tasks/gulp/__tests__/after-build-package.test.mjs
  tasks/gulp/copy-to-destination.mjs
  tasks/gulp/watch.mjs
  tasks/screenshot-components.mjs
  tasks/task-arguments.mjs
  tasks/task-arguments.unit.test.mjs
Labels: consistency

#3380 Build tasks: Fix various JSDoc types
  jest-dev-server.config.js
  jest-puppeteer.config.js
  package-lock.json
  package.json
  tasks/compile-assets.mjs
  tasks/compile-javascripts.mjs
  tasks/compile-stylesheets.mjs
  tasks/gulp/copy-to-destination.mjs
  tasks/run.mjs
Labels: javascript, consistency, interoperability

#3391 Webpack example: Add configs for PostCSS, Babel, Browserslist
  docs/examples/webpack/.browserslistrc
  docs/examples/webpack/assets/stylesheets/app-ie8.scss
  docs/examples/webpack/babel.config.mjs
  docs/examples/webpack/index.html
  docs/examples/webpack/package.json
  docs/examples/webpack/postcss.config.mjs
  docs/examples/webpack/webpack.config.js
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  postcss.config.unit.test.mjs
Labels: documentation, interoperability, tooling

#3390 Webpack example: Remove IE8 support
  docs/examples/webpack/assets/stylesheets/app-ie8.scss
  docs/examples/webpack/index.html
  docs/examples/webpack/package.json
  docs/examples/webpack/webpack.config.js
  package-lock.json
Labels: documentation, sass / css, tooling

#3372 Build tasks: Create tasks per target without `--destination`
  docs/contributing/tasks.md
  gulpfile.mjs
  lib/file-helper.js
  package.json
  tasks/asset-version.mjs
  tasks/clean.mjs
  tasks/clean.unit.test.mjs
  tasks/compile-assets.mjs
  tasks/compile-configs.mjs
  tasks/compile-javascripts.mjs
  tasks/compile-stylesheets.mjs
  tasks/file.mjs
  tasks/gulp/copy-to-destination.mjs
  tasks/prototype-kit-config.mjs
  tasks/task-arguments.mjs
  tasks/task-arguments.unit.test.mjs
Labels: consistency

#3401 Build tasks: Consolidate browser screenshot script as tasks
  config/jest/browser/open.mjs
  gulpfile.mjs
  package.json
  tasks/browser.mjs
  tasks/browser.unit.test.mjs
  tasks/browser/download.mjs
Labels: consistency

#3411 Fix for missing review app packages
  package-lock.json
  package.json
Labels: 🐛 bug

#3383 Build tasks: Move review app files into `app/dist`
  .eslintrc.js
  .github/workflows/actions/build/action.yml
  .gitignore
  .prettierignore
  app/src/common/middleware/assets.mjs
  app/src/common/middleware/docs.mjs
  config/paths.js
  docs/contributing/application-architecture.md
  docs/contributing/tasks.md
  gulpfile.mjs
  jsdoc.config.js
  postcss.config.mjs
  postcss.config.unit.test.mjs
  sassdoc.config.yaml
  stylelint.config.js
  tasks/build/app.mjs
Labels: consistency

#3426 Support government changes - Update the labelling
  src/govuk/settings/_colours-organisations.scss
Labels: awaiting triage

#3439 Fix argument count in deprecated `this.mql.addListener()`
  src/govuk/components/header/header.mjs
Labels: 🐛 bug
