Repository alphagov/govuk-frontend, pull requests merged in 2023-11, with the labels that each got.

#4422 Fix rate limit issue with EditorConfig checker CLI
  .github/workflows/diff-change-to-dist.yaml
  .github/workflows/stats-comment.yml
  .github/workflows/tests.yml
Labels: 🐛 bug, github_actions

#4462 Fix various bugs in Review app
  packages/govuk-frontend-review/nodemon.json
  packages/govuk-frontend-review/src/app.mjs
  packages/govuk-frontend-review/src/app.puppeteer.test.mjs
  packages/govuk-frontend-review/src/routes/full-page-examples.mjs
  packages/govuk-frontend-review/src/views/components.njk
  packages/govuk-frontend-review/src/views/index.njk
  packages/govuk-frontend-review/src/views/macros/showExamples.njk
Labels: 🐛 bug

#4463 Add error pages to Review app
  packages/govuk-frontend-review/src/app.mjs
  packages/govuk-frontend-review/src/common/lib/files.mjs
  packages/govuk-frontend-review/src/common/nunjucks/filters/index.mjs
  packages/govuk-frontend-review/src/common/nunjucks/filters/inspect.mjs
  packages/govuk-frontend-review/src/common/nunjucks/globals/get-nunjucks-code.mjs
  packages/govuk-frontend-review/src/routes/full-page-examples.mjs
  packages/govuk-frontend-review/src/views/component.njk
  packages/govuk-frontend-review/src/views/components.njk
  packages/govuk-frontend-review/src/views/errors/404.njk
  packages/govuk-frontend-review/src/views/errors/500.njk
  packages/govuk-frontend-review/src/views/full-page-examples/index.njk
Labels: assurance

#4417 Add HTML validation rules for missing elements
  packages/govuk-frontend/.htmlvalidate.js
  packages/govuk-frontend/src/govuk/components/button/button.yaml
  packages/govuk-frontend/src/govuk/components/button/template.test.js
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
  packages/govuk-frontend/src/govuk/components/checkboxes/template.test.js
  packages/govuk-frontend/src/govuk/components/components.template.test.js
  packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
  packages/govuk-frontend/src/govuk/components/date-input/template.test.js
  packages/govuk-frontend/src/govuk/components/fieldset/fieldset.yaml
  packages/govuk-frontend/src/govuk/components/fieldset/template.test.js
  packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
  packages/govuk-frontend/src/govuk/components/file-upload/template.test.js
  packages/govuk-frontend/src/govuk/components/input/input.yaml
  packages/govuk-frontend/src/govuk/components/input/template.test.js
  packages/govuk-frontend/src/govuk/components/label/label.yaml
  packages/govuk-frontend/src/govuk/components/label/template.test.js
  packages/govuk-frontend/src/govuk/components/radios/radios.yaml
  packages/govuk-frontend/src/govuk/components/radios/template.test.js
  packages/govuk-frontend/src/govuk/components/select/select.yaml
  packages/govuk-frontend/src/govuk/components/select/template.test.js
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.yaml
  packages/govuk-frontend/src/govuk/components/textarea/template.test.js
  packages/govuk-frontend/src/govuk/components/textarea/textarea.yaml
  packages/govuk-frontend/src/govuk/template.test.js
  shared/lib/components.js
Labels: accessibility, assurance

#4416 Review and fix HTML attribute trailing spaces etc
  packages/govuk-frontend-review/src/views/component-preview.njk
  packages/govuk-frontend-review/src/views/component.njk
  packages/govuk-frontend-review/src/views/components.njk
  packages/govuk-frontend/src/govuk/components/accordion/template.njk
  packages/govuk-frontend/src/govuk/components/back-link/template.njk
  packages/govuk-frontend/src/govuk/components/breadcrumbs/template.njk
  packages/govuk-frontend/src/govuk/components/button/template.njk
  packages/govuk-frontend/src/govuk/components/character-count/template.njk
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
  packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
  packages/govuk-frontend/src/govuk/components/cookie-banner/cookie-banner.yaml
  packages/govuk-frontend/src/govuk/components/cookie-banner/template.njk
  packages/govuk-frontend/src/govuk/components/date-input/template.njk
  packages/govuk-frontend/src/govuk/components/details/template.njk
  packages/govuk-frontend/src/govuk/components/error-message/template.njk
  packages/govuk-frontend/src/govuk/components/error-summary/template.njk
  packages/govuk-frontend/src/govuk/components/exit-this-page/template.njk
  packages/govuk-frontend/src/govuk/components/file-upload/template.njk
  packages/govuk-frontend/src/govuk/components/footer/template.njk
  packages/govuk-frontend/src/govuk/components/header/template.njk
  packages/govuk-frontend/src/govuk/components/hint/template.njk
  packages/govuk-frontend/src/govuk/components/input/template.njk
  packages/govuk-frontend/src/govuk/components/inset-text/template.njk
  packages/govuk-frontend/src/govuk/components/label/template.njk
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.yaml
  packages/govuk-frontend/src/govuk/components/notification-banner/template.njk
  packages/govuk-frontend/src/govuk/components/notification-banner/template.test.js
  packages/govuk-frontend/src/govuk/components/pagination/template.njk
  packages/govuk-frontend/src/govuk/components/panel/template.njk
  packages/govuk-frontend/src/govuk/components/phase-banner/template.njk
  packages/govuk-frontend/src/govuk/components/radios/template.njk
  packages/govuk-frontend/src/govuk/components/select/template.njk
  packages/govuk-frontend/src/govuk/components/skip-link/template.njk
  packages/govuk-frontend/src/govuk/components/summary-list/template.njk
  packages/govuk-frontend/src/govuk/components/table/template.njk
  packages/govuk-frontend/src/govuk/components/tabs/template.njk
  packages/govuk-frontend/src/govuk/components/tag/template.njk
  packages/govuk-frontend/src/govuk/components/task-list/template.njk
  packages/govuk-frontend/src/govuk/components/textarea/template.njk
  packages/govuk-frontend/src/govuk/components/warning-text/template.njk
  packages/govuk-frontend/src/govuk/template.njk
Labels: nunjucks

#3977 Add pre-release documentation with version numbers
  docs/releasing/publishing-a-pre-release.md
  docs/releasing/publishing-a-preview.md
  docs/releasing/publishing.md
Labels: documentation

#4450 Update descriptions for Nunjucks macro options + fixes
  packages/govuk-frontend/src/govuk/components/accordion/accordion.yaml
  packages/govuk-frontend/src/govuk/components/back-link/back-link.yaml
  packages/govuk-frontend/src/govuk/components/breadcrumbs/breadcrumbs.yaml
  packages/govuk-frontend/src/govuk/components/button/button.yaml
  packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
  packages/govuk-frontend/src/govuk/components/cookie-banner/cookie-banner.yaml
  packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
  packages/govuk-frontend/src/govuk/components/error-message/error-message.yaml
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.yaml
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.yaml
  packages/govuk-frontend/src/govuk/components/fieldset/fieldset.yaml
  packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
  packages/govuk-frontend/src/govuk/components/footer/footer.yaml
  packages/govuk-frontend/src/govuk/components/header/header.yaml
  packages/govuk-frontend/src/govuk/components/input/input.yaml
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.yaml
  packages/govuk-frontend/src/govuk/components/pagination/pagination.yaml
  packages/govuk-frontend/src/govuk/components/phase-banner/phase-banner.yaml
  packages/govuk-frontend/src/govuk/components/radios/radios.yaml
  packages/govuk-frontend/src/govuk/components/select/select.yaml
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.yaml
  packages/govuk-frontend/src/govuk/components/summary-list/summary-list.yaml
  packages/govuk-frontend/src/govuk/components/table/table.yaml
  packages/govuk-frontend/src/govuk/components/tabs/tabs.yaml
  packages/govuk-frontend/src/govuk/components/task-list/task-list.yaml
  packages/govuk-frontend/src/govuk/components/textarea/textarea.yaml
  packages/govuk-frontend/src/govuk/components/warning-text/warning-text.yaml
Labels: documentation, nunjucks

#4492 Improve SupportError when `<body class="govuk-frontend-supported">` is not set
  CHANGELOG.md
  packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
  packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
  packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
  packages/govuk-frontend/src/govuk/errors/index.mjs
Labels: javascript

#4494 Fix missed `actions/setup-node` update
  .github/workflows/actions/setup-node/action.yml
Labels: dependencies

#4495 Fix Review app banner on cookie banner full page examples
  packages/govuk-frontend-review/src/app.mjs
  packages/govuk-frontend-review/src/app.puppeteer.test.mjs
  packages/govuk-frontend-review/src/common/middleware/banner.mjs
  packages/govuk-frontend-review/src/common/middleware/banner.unit.test.mjs
  packages/govuk-frontend-review/src/common/middleware/index.mjs
  packages/govuk-frontend-review/src/common/middleware/request.mjs
  packages/govuk-frontend-review/src/routes/banner.mjs
  packages/govuk-frontend-review/src/routes/banner.puppeteer.test.mjs
  packages/govuk-frontend-review/src/routes/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-client-side/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-essential-cookies/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-server-side/index.njk
Labels: 🐛 bug

#4518 Update last mentions of Internet Explorer
  CONTRIBUTING.md
  README.md
  docs/contributing/browser-support.md
  docs/contributing/resize-text-in-browsers.md
  docs/contributing/testing.md
Labels: documentation
