Repository alphagov/govuk-frontend, pull requests merged in 2023-05, with the labels that each got.

#3560 Update packages to follow GOV.UK Frontend docs
  app/package.json
  app/src/common/middleware/assets.mjs
  app/src/stylesheets/app-ie8.scss
  app/src/stylesheets/app.scss
  app/src/stylesheets/full-page-examples/campaign-page.scss
  app/src/stylesheets/full-page-examples/search.scss
  app/tasks/assets.mjs
  app/tasks/build/dist.mjs
  app/tasks/clean.mjs
  app/tasks/index.mjs
  app/tsconfig.json
  docs/examples/webpack/src/assets/stylesheets/app.scss
  docs/examples/webpack/webpack.config.js
  package-lock.json
  shared/tasks/package.json
  shared/tasks/scripts.mjs
  shared/tasks/styles.mjs
Labels: documentation, assurance

#3562 Prepare Gulp tasks + helpers for directory changes
  .github/workflows/screenshots.yml
  .github/workflows/tests.yml
  app/gulpfile.mjs
  app/package.json
  app/tasks/build/dev.mjs
  app/tasks/build/dist.mjs
  app/tasks/build/options.mjs
  app/tasks/scripts.mjs
  app/tasks/styles.mjs
  app/tasks/watch.mjs
  bin/build-release.sh
  docs/contributing/application-architecture.md
  docs/contributing/coding-standards/css.md
  docs/contributing/managing-change.md
  docs/contributing/tasks.md
  docs/contributing/testing.md
  docs/releasing/publishing-a-pre-release.md
  docs/releasing/publishing-from-a-support-branch.md
  docs/releasing/publishing.md
  docs/releasing/testing-and-linting.md
  gulpfile.mjs
  package.json
  package/README.md
  shared/config/paths.js
  shared/lib/files.js
  shared/tasks/assets.mjs
  shared/tasks/build/index.mjs
  shared/tasks/build/package.mjs
  shared/tasks/build/package.test.mjs
  shared/tasks/build/release.mjs
  shared/tasks/build/release.test.mjs
  shared/tasks/files.mjs
  shared/tasks/helpers/task-arguments.unit.test.mjs
  shared/tasks/index.mjs
  shared/tasks/npm.mjs
  shared/tasks/task.mjs
  src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
Labels: tooling

#3561 Use JSDoc `@satisfies` for query selector inheritance
  package-lock.json
  package.json
  src/govuk/common/govuk-frontend-version.mjs
  src/govuk/components/checkboxes/checkboxes.mjs
  src/govuk/components/radios/radios.mjs
  src/govuk/components/tabs/tabs.mjs
  src/tsconfig.build.json
  src/tsconfig.json
  typedoc.config.js
Labels: assurance, interoperability

#3570 Remove IE8-10 JavaScript polyfills, helpers, config
  .github/dependabot.yml
  docs/contributing/coding-standards/js.md
  docs/contributing/polyfilling.md
  package-lock.json
  package.json.unit.test.js
  packages/govuk-frontend-review/package.json
  packages/govuk-frontend-review/src/common/middleware/vendor.mjs
  packages/govuk-frontend-review/src/views/component-preview.njk
  packages/govuk-frontend-review/src/views/examples/scoped-initialisation/index.njk
  packages/govuk-frontend-review/src/views/examples/template-custom/index.njk
  packages/govuk-frontend-review/src/views/examples/template-default/index.njk
  packages/govuk-frontend-review/src/views/layouts/layout.njk
  packages/govuk-frontend/.eslintrc.js
  packages/govuk-frontend/src/govuk/all.mjs
  packages/govuk-frontend/src/govuk/common/index.mjs
  packages/govuk-frontend/src/govuk/common/index.unit.test.mjs
  packages/govuk-frontend/src/govuk/common/normalise-dataset.mjs
  packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
  packages/govuk-frontend/src/govuk/components/button/button.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
  packages/govuk-frontend/src/govuk/components/details/details.mjs
  packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
  packages/govuk-frontend/src/govuk/components/header/header.mjs
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
  packages/govuk-frontend/src/govuk/components/radios/radios.mjs
  packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
  packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Date/now.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Document.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Element.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Element/prototype/classList.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Element/prototype/dataset.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Element/prototype/nextElementSibling.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Element/prototype/previousElementSibling.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Event.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Function/prototype/bind.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Object/defineProperty.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/String/prototype/trim.mjs
  packages/govuk-frontend/src/govuk/vendor/polyfills/Window.mjs
  shared/lib/names.unit.test.mjs
  shared/tasks/package.json
  shared/tasks/scripts.mjs
Labels: javascript, interoperability

#3584 Fix URL `file://` path handling on Windows
  .github/workflows/actions/build/action.yml
  .github/workflows/tests.yml
  shared/tasks/assets.mjs
  shared/tasks/configs.mjs
Labels: 🐛 bug

#3582 Add warning about forking the repository while we work on v5
  README.md
Labels: documentation

#3620 Move config files into their related packages
  babel.config.js
  package-lock.json
  package.json
  packages/govuk-frontend-review/package.json
  packages/govuk-frontend-review/postcss.config.mjs
  packages/govuk-frontend-review/postcss.config.unit.test.mjs
  packages/govuk-frontend-review/sassdoc.config.yaml
  packages/govuk-frontend-review/tasks/scripts.mjs
  packages/govuk-frontend-review/tasks/styles.mjs
  packages/govuk-frontend-review/typedoc.config.js
  packages/govuk-frontend/.browserslistrc
  packages/govuk-frontend/package.json
  packages/govuk-frontend/postcss.config.mjs
  packages/govuk-frontend/postcss.config.unit.test.mjs
  postcss.config.mjs
  postcss.config.unit.test.mjs
  shared/tasks/styles.mjs
Labels: consistency, tooling

#3623 Compile GOV.UK Prototype Kit config to package top level
  bin/pre-release.sh
  packages/govuk-frontend/.gitignore
  packages/govuk-frontend/package.json
  packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
  packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs
  packages/govuk-frontend/tasks/build/package.test.mjs
  packages/govuk-frontend/tasks/scripts.mjs
Labels: interoperability

#3645 Ensure component data types are correct
  shared/helpers/nunjucks.js
  shared/lib/files.js
  shared/tasks/components.mjs
Labels: interoperability

#3650 Ensure GitHub Actions runs type declaration checks in all files
  package.json
  packages/govuk-frontend/tsconfig.json
  tsconfig.base.json
Labels: assurance

#3647 Ensure shared task `options` are mandatory unless specified
  package-lock.json
  package.json
  packages/govuk-frontend-review/tasks/scripts.mjs
  packages/govuk-frontend-review/tasks/styles.mjs
  packages/govuk-frontend-review/tsconfig.json
  packages/govuk-frontend/tasks/build/package.mjs
  packages/govuk-frontend/tasks/build/release.mjs
  packages/govuk-frontend/tasks/scripts.mjs
  packages/govuk-frontend/tasks/styles.mjs
  shared/tasks/assets.mjs
  shared/tasks/components.mjs
  shared/tasks/configs.mjs
  shared/tasks/files.mjs
  shared/tasks/index.mjs
  shared/tasks/scripts.mjs
  shared/tasks/styles.mjs
Labels: interoperability

#3648 Configure tasks to use `rollup.config.mjs` files
  package-lock.json
  packages/govuk-frontend-review/package.json
  packages/govuk-frontend-review/rollup.config.mjs
  packages/govuk-frontend-review/tasks/scripts.mjs
  packages/govuk-frontend/package.json
  packages/govuk-frontend/rollup.esm.config.mjs
  packages/govuk-frontend/rollup.release.config.mjs
  packages/govuk-frontend/rollup.umd.config.mjs
  packages/govuk-frontend/tasks/build/package.test.mjs
  packages/govuk-frontend/tasks/build/release.mjs
  packages/govuk-frontend/tasks/scripts.mjs
  shared/tasks/assets.mjs
  shared/tasks/package.json
  shared/tasks/scripts.mjs
  shared/tasks/styles.mjs
Labels: javascript, tooling

#3649 Configure paths to `postcss.config.mjs` files
  packages/govuk-frontend-review/tasks/styles.mjs
  packages/govuk-frontend/tasks/build/release.mjs
  packages/govuk-frontend/tasks/styles.mjs
  shared/tasks/assets.mjs
  shared/tasks/styles.mjs
Labels: sass / css, tooling

#3543 Switch to new Chrome headless mode
  jest-puppeteer.config.js
  jest.config.mjs
  packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js
  shared/tasks/browser.mjs
Labels: assurance

#3683 Silence markdown deprecation warnings
  package-lock.json
  package.json
  packages/govuk-frontend-review/src/common/nunjucks/globals/markdown.mjs
Labels: javascript, tooling

#3690 Add Browsersync on `http://localhost:3000`
  package-lock.json
  package.json
  packages/govuk-frontend-review/browsersync.config.js
  packages/govuk-frontend-review/nodemon.json
  packages/govuk-frontend-review/package.json
  packages/govuk-frontend-review/tasks/build/dev.mjs
  shared/config/ports.js
Labels: usability, tooling

#3691 Add Browsersync reload on `*.js` changes in review app
  packages/govuk-frontend-review/browsersync.config.js
Labels: 🐛 bug

#3692 Fix a few more `govuk` → `dist/govuk` references
  docs/contributing/managing-change.md
  packages/govuk-frontend/README.md
Labels: documentation

#3694 Fix missing "Update your account details" error messages etc
  packages/govuk-frontend-review/src/utils.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/feedback/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/have-you-changed-your-name/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/how-do-you-want-to-sign-in/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/passport-details/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/update-your-account-details/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.mjs
Labels: 🐛 bug

#3724 Add shared `getYaml()` lib function
  package-lock.json
  shared/lib/files.js
  shared/tasks/components.mjs
  shared/tasks/package.json
Labels: tooling
