Repository alphagov/govuk-frontend, pull requests merged in 2023-04, with the labels that each got.

#3472 Bump minimum Ruby Sass v3.4.0 test bundler version (again)
  .github/workflows/sass.yaml
Labels: assurance, dependencies

#3386 Compile ES modules using Rollup
  docs/contributing/coding-standards/js.md
  docs/contributing/tasks.md
  tasks/build/package.mjs
  tasks/build/package.test.mjs
  tasks/scripts.mjs
Labels: feature request, javascript

#3456 Refactor file copying tasks to remove Gulp
  package-lock.json
  package.json
  tasks/assets.mjs
  tasks/build/package.mjs
  tasks/components.mjs
  tasks/configs.mjs
  tasks/files.mjs
  tasks/gulp/copy-to-destination.mjs
  tasks/index.mjs
  tasks/task.mjs
Labels: tooling

#3493 Add (optional) type declaration checks in all files
  app/tsconfig.json
  config/tsconfig.json
  lib/puppeteer-helpers.js
  lib/tsconfig.json
  package-lock.json
  package.json
  src/govuk-prototype-kit/init.js
  src/govuk/common/closest-attribute-value.unit.test.mjs
  src/govuk/common/index.unit.test.mjs
  src/govuk/common/normalise-dataset.unit.test.mjs
  src/govuk/components/accordion/accordion.test.js
  src/govuk/components/button/button.test.js
  src/govuk/components/character-count/character-count.test.js
  src/govuk/components/error-summary/error-summary.test.js
  src/govuk/components/globals.test.mjs
  src/govuk/components/notification-banner/notification-banner.test.js
  src/govuk/components/skip-link/skip-link.test.js
  src/govuk/helpers/colour.test.js
  src/govuk/helpers/media-queries.test.js
  src/govuk/i18n.unit.test.mjs
  src/govuk/tools/compatibility.test.js
  src/govuk/tools/exports.test.js
  src/govuk/tools/font-url.test.js
  src/govuk/tools/ie8.test.js
  src/govuk/tools/image-url.test.js
  src/tsconfig.build.json
  src/tsconfig.json
  tasks/browser.mjs
  tasks/browser.unit.test.mjs
  tasks/build/package.test.mjs
  tasks/scripts.mjs
  tasks/styles.mjs
  tasks/tsconfig.json
  tsconfig.base.json
  tsconfig.build.json
  tsconfig.json
Labels: javascript, consistency, interoperability, dependencies

#3412 Reduce dependencies for review app
  lib/file-helper.js
  lib/jest-helpers.js
  lib/nunjucks-helpers.js
  lib/puppeteer-helpers.js
  package-lock.json
  package.json
  src/govuk/components/accordion/accordion.test.js
  src/govuk/components/accordion/template.test.js
  src/govuk/components/back-link/template.test.js
  src/govuk/components/breadcrumbs/template.test.js
  src/govuk/components/button/button.test.js
  src/govuk/components/button/template.test.js
  src/govuk/components/character-count/character-count.test.js
  src/govuk/components/character-count/template.test.js
  src/govuk/components/checkboxes/template.test.js
  src/govuk/components/components.template.test.js
  src/govuk/components/cookie-banner/template.test.js
  src/govuk/components/date-input/template.test.js
  src/govuk/components/details/template.test.js
  src/govuk/components/error-message/template.test.js
  src/govuk/components/error-summary/error-summary.test.js
  src/govuk/components/error-summary/template.test.js
  src/govuk/components/fieldset/template.test.js
  src/govuk/components/file-upload/template.test.js
  src/govuk/components/footer/template.test.js
  src/govuk/components/header/template.test.js
  src/govuk/components/hint/template.test.js
  src/govuk/components/input/template.test.js
  src/govuk/components/inset-text/template.test.js
  src/govuk/components/label/template.test.js
  src/govuk/components/notification-banner/notification-banner.test.js
  src/govuk/components/notification-banner/template.test.js
  src/govuk/components/pagination/template.test.js
  src/govuk/components/panel/template.test.js
  src/govuk/components/phase-banner/template.test.js
  src/govuk/components/radios/template.test.js
  src/govuk/components/select/template.test.js
  src/govuk/components/skip-link/template.test.js
  src/govuk/components/summary-list/template.test.js
  src/govuk/components/table/template.test.js
  src/govuk/components/tabs/template.test.js
  src/govuk/components/tag/template.test.js
  src/govuk/components/textarea/template.test.js
  src/govuk/components/warning-text/template.test.js
  src/govuk/macros/i18n.unit.test.mjs
  src/govuk/template.test.js
Labels: 🐛 bug

#3501 Include "Review app" in `npm run build:types` check
  app/src/app.mjs
  app/src/common/middleware/legacy.mjs
  app/src/common/middleware/legacy.test.mjs
  app/src/common/middleware/request.test.mjs
  app/src/common/middleware/robots.test.mjs
  app/src/routes/banner.mjs
  app/src/routes/full-page-examples.mjs
  app/src/routes/full-page-examples.test.mjs
  app/src/views/full-page-examples/applicant-details/index.mjs
  app/src/views/full-page-examples/cookie-banner-essential-cookies/index.mjs
  app/src/views/full-page-examples/cookie-banner-server-side/index.mjs
  app/src/views/full-page-examples/feedback/index.mjs
  app/src/views/full-page-examples/have-you-changed-your-name/index.mjs
  app/src/views/full-page-examples/how-do-you-want-to-sign-in/index.mjs
  app/src/views/full-page-examples/passport-details/index.mjs
  app/src/views/full-page-examples/search/index.mjs
  app/src/views/full-page-examples/update-your-account-details/index.mjs
  app/src/views/full-page-examples/upload-your-photo-success/index.mjs
  app/src/views/full-page-examples/upload-your-photo/index.mjs
  app/src/views/full-page-examples/what-is-your-address/index.mjs
  app/src/views/full-page-examples/what-is-your-nationality/index.mjs
  app/src/views/full-page-examples/what-is-your-postcode/index.mjs
  app/src/views/full-page-examples/what-was-the-last-country-you-visited/index.mjs
  app/tsconfig.build.json
  package-lock.json
  package.json
  tsconfig.build.json
Labels: assurance, consistency

#3500 Return `render()` and `renderTemplate()` helpers via cheerio
  app/src/app.mjs
  package-lock.json
  package.json
  shared/helpers/nunjucks.js
  shared/helpers/puppeteer.js
  src/govuk/components/accordion/template.test.js
  src/govuk/components/back-link/template.test.js
  src/govuk/components/breadcrumbs/template.test.js
  src/govuk/components/button/template.test.js
  src/govuk/components/character-count/template.test.js
  src/govuk/components/checkboxes/template.test.js
  src/govuk/components/components.template.test.js
  src/govuk/components/cookie-banner/template.test.js
  src/govuk/components/date-input/template.test.js
  src/govuk/components/details/template.test.js
  src/govuk/components/error-message/template.test.js
  src/govuk/components/error-summary/template.test.js
  src/govuk/components/fieldset/template.test.js
  src/govuk/components/file-upload/template.test.js
  src/govuk/components/footer/template.test.js
  src/govuk/components/header/template.test.js
  src/govuk/components/hint/template.test.js
  src/govuk/components/input/template.test.js
  src/govuk/components/inset-text/template.test.js
  src/govuk/components/label/template.test.js
  src/govuk/components/notification-banner/template.test.js
  src/govuk/components/pagination/template.test.js
  src/govuk/components/panel/template.test.js
  src/govuk/components/phase-banner/template.test.js
  src/govuk/components/radios/template.test.js
  src/govuk/components/select/template.test.js
  src/govuk/components/skip-link/template.test.js
  src/govuk/components/summary-list/template.test.js
  src/govuk/components/table/template.test.js
  src/govuk/components/tabs/template.test.js
  src/govuk/components/tag/template.test.js
  src/govuk/components/textarea/template.test.js
  src/govuk/components/warning-text/template.test.js
  src/govuk/template.test.js
Labels: tech debt

#3512 Switch JSDoc parser to TypeDoc + fix issues
  .lintstagedrc.js
  app/tasks/watch.mjs
  jsdoc.config.js
  package-lock.json
  package.json
  shared/helpers/nunjucks.js
  shared/helpers/puppeteer.js
  shared/lib/files.js
  shared/tasks/assets.mjs
  shared/tasks/browser.mjs
  shared/tasks/components.mjs
  shared/tasks/files.mjs
  shared/tasks/scripts.mjs
  shared/tasks/styles.mjs
  shared/tasks/task.mjs
  src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
  src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs
  src/govuk/all.mjs
  src/govuk/common/index.mjs
  src/govuk/common/normalise-dataset.mjs
  src/govuk/components/accordion/accordion.mjs
  src/govuk/components/button/button.mjs
  src/govuk/components/character-count/character-count.mjs
  src/govuk/components/details/details.mjs
  src/govuk/components/error-summary/error-summary.mjs
  src/govuk/components/notification-banner/notification-banner.mjs
  src/govuk/i18n.mjs
  src/govuk/i18n.unit.test.mjs
  typedoc.config.js
Labels: documentation, javascript

#3530 Remove incorrect information about visually hidden text on previous/next
  src/govuk/components/pagination/pagination.yaml
Labels: awaiting triage

#3319 Add (mandatory) type declaration checks
  .eslintrc.js
  .github/workflows/tests.yml
  package-lock.json
  package.json
  src/.eslintrc.js
  src/govuk/common/index.mjs
  src/govuk/components/button/button.mjs
  src/govuk/components/character-count/character-count.mjs
  src/govuk/components/header/header.mjs
  src/govuk/vendor/polyfills/DOMTokenList.mjs
  src/govuk/vendor/polyfills/Date/now.mjs
  src/govuk/vendor/polyfills/Document.mjs
  src/govuk/vendor/polyfills/Element.mjs
  src/govuk/vendor/polyfills/Element/prototype/classList.mjs
  src/govuk/vendor/polyfills/Element/prototype/closest.mjs
  src/govuk/vendor/polyfills/Element/prototype/dataset.mjs
  src/govuk/vendor/polyfills/Element/prototype/matches.mjs
  src/govuk/vendor/polyfills/Element/prototype/nextElementSibling.mjs
  src/govuk/vendor/polyfills/Element/prototype/previousElementSibling.mjs
  src/govuk/vendor/polyfills/Event.mjs
  src/govuk/vendor/polyfills/Function/prototype/bind.mjs
  src/govuk/vendor/polyfills/Object/defineProperty.mjs
  src/govuk/vendor/polyfills/String/prototype/trim.mjs
  src/govuk/vendor/polyfills/Window.mjs
Labels: javascript, consistency, interoperability, dependencies

#3542 Prevent Chrome headless deprecation warning
  jest-puppeteer.config.js
Labels: 🐛 bug, github-actions

#3551 Fix cross-realm object access in Webpack 5
  .github/workflows/actions/build/action.yml
  package-lock.json
Labels: dependencies, security

#3558 Use `npm version` for version bumps
  bin/build-release.sh
  bin/generate-npm-tag.sh
  docs/contributing/testing.md
  docs/releasing/publishing-a-pre-release.md
  docs/releasing/publishing-from-a-support-branch.md
  docs/releasing/publishing.md
Labels: 🐛 bug

#3555 Update “caniuse” data with `npx update-browserslist-db@latest`
  docs/releasing/publishing.md
  package-lock.json
Labels: assurance, dependencies
