Repository alphagov/govuk-frontend, pull requests merged in 2024-02, with the labels that each got.

#4674 Fix Nunjucks HTML indentation: Fieldset, Label and Hint
  packages/govuk-frontend/src/govuk/components/character-count/template.njk
  packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
  packages/govuk-frontend/src/govuk/components/date-input/template.njk
  packages/govuk-frontend/src/govuk/components/fieldset/template.njk
  packages/govuk-frontend/src/govuk/components/hint/template.njk
  packages/govuk-frontend/src/govuk/components/hint/template.test.js
  packages/govuk-frontend/src/govuk/components/label/template.njk
  packages/govuk-frontend/src/govuk/components/radios/template.njk
Labels: nunjucks

#4675 Fix Nunjucks HTML indentation: Error message and summary
  packages/govuk-frontend/src/govuk/components/error-message/template.njk
  packages/govuk-frontend/src/govuk/components/error-summary/template.njk
Labels: nunjucks

#4707 Fix Nunjucks HTML indentation: Text input
  packages/govuk-frontend/src/govuk/components/input/template.njk
Labels: nunjucks

#4705 Fix Nunjucks HTML indentation: Inset text
  packages/govuk-frontend/src/govuk/components/inset-text/template.njk
  packages/govuk-frontend/src/govuk/components/inset-text/template.test.js
Labels: nunjucks

#4678 Fix Nunjucks HTML indentation: Cookie banner
  packages/govuk-frontend/src/govuk/components/cookie-banner/template.njk
  packages/govuk-frontend/src/govuk/components/cookie-banner/template.test.js
Labels: nunjucks

#4706 Fix Nunjucks HTML indentation: Notification banner
  packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.yaml
  packages/govuk-frontend/src/govuk/components/notification-banner/template.njk
  packages/govuk-frontend/src/govuk/components/notification-banner/template.test.js
Labels: nunjucks

#4679 Fix Nunjucks HTML indentation: Details
  packages/govuk-frontend/src/govuk/components/details/template.njk
Labels: nunjucks

#4715 Fix Nunjucks HTML indentation: Panel, Phase banner
  packages/govuk-frontend/src/govuk/components/panel/template.njk
  packages/govuk-frontend/src/govuk/components/phase-banner/template.njk
Labels: nunjucks

#4712 Fix Nunjucks HTML indentation: Select
  packages/govuk-frontend/src/govuk/components/select/template.njk
Labels: nunjucks

#4567 Add `beforeInput(s)` and `afterInput(s)` options to form groups
  CHANGELOG.md
  packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml
  packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
  packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
  packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
  packages/govuk-frontend/src/govuk/components/date-input/template.njk
  packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
  packages/govuk-frontend/src/govuk/components/file-upload/template.njk
  packages/govuk-frontend/src/govuk/components/input/input.yaml
  packages/govuk-frontend/src/govuk/components/input/template.njk
  packages/govuk-frontend/src/govuk/components/radios/radios.yaml
  packages/govuk-frontend/src/govuk/components/radios/template.njk
  packages/govuk-frontend/src/govuk/components/select/select.yaml
  packages/govuk-frontend/src/govuk/components/select/template.njk
  packages/govuk-frontend/src/govuk/components/textarea/template.njk
  packages/govuk-frontend/src/govuk/components/textarea/textarea.yaml
Labels: nunjucks

#4742 Add macro `govukAttributes()` with `params.attributes` string support
  packages/govuk-frontend/src/govuk/components/accordion/template.njk
  packages/govuk-frontend/src/govuk/components/back-link/template.njk
  packages/govuk-frontend/src/govuk/components/breadcrumbs/template.njk
  packages/govuk-frontend/src/govuk/components/button/template.njk
  packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
  packages/govuk-frontend/src/govuk/components/cookie-banner/template.njk
  packages/govuk-frontend/src/govuk/components/date-input/template.njk
  packages/govuk-frontend/src/govuk/components/details/template.njk
  packages/govuk-frontend/src/govuk/components/error-message/template.njk
  packages/govuk-frontend/src/govuk/components/error-summary/template.njk
  packages/govuk-frontend/src/govuk/components/exit-this-page/template.njk
  packages/govuk-frontend/src/govuk/components/fieldset/template.njk
  packages/govuk-frontend/src/govuk/components/file-upload/template.njk
  packages/govuk-frontend/src/govuk/components/footer/template.njk
  packages/govuk-frontend/src/govuk/components/header/template.njk
  packages/govuk-frontend/src/govuk/components/hint/template.njk
  packages/govuk-frontend/src/govuk/components/input/template.njk
  packages/govuk-frontend/src/govuk/components/inset-text/template.njk
  packages/govuk-frontend/src/govuk/components/label/template.njk
  packages/govuk-frontend/src/govuk/components/notification-banner/template.njk
  packages/govuk-frontend/src/govuk/components/pagination/template.njk
  packages/govuk-frontend/src/govuk/components/panel/template.njk
  packages/govuk-frontend/src/govuk/components/phase-banner/template.njk
  packages/govuk-frontend/src/govuk/components/radios/template.njk
  packages/govuk-frontend/src/govuk/components/select/template.njk
  packages/govuk-frontend/src/govuk/components/skip-link/template.njk
  packages/govuk-frontend/src/govuk/components/summary-list/template.njk
  packages/govuk-frontend/src/govuk/components/table/template.njk
  packages/govuk-frontend/src/govuk/components/tabs/template.njk
  packages/govuk-frontend/src/govuk/components/tag/template.njk
  packages/govuk-frontend/src/govuk/components/task-list/template.njk
  packages/govuk-frontend/src/govuk/components/textarea/template.njk
  packages/govuk-frontend/src/govuk/components/warning-text/template.njk
  packages/govuk-frontend/src/govuk/macros/attributes.njk
  packages/govuk-frontend/src/govuk/macros/attributes.unit.test.mjs
  packages/govuk-frontend/src/govuk/template.njk
  shared/lib/components.js
Labels: nunjucks

#4717 Fix Nunjucks HTML indentation: Table
  packages/govuk-frontend/src/govuk/components/table/template.njk
Labels: nunjucks

#4716 Fix Nunjucks HTML indentation: Summary list
  packages/govuk-frontend/src/govuk/components/summary-list/template.njk
Labels: nunjucks

#4704 Fix Nunjucks HTML indentation: Footer
  packages/govuk-frontend/src/govuk/components/footer/template.njk
Labels: nunjucks

#4710 Fix Nunjucks HTML indentation: Pagination
  packages/govuk-frontend/src/govuk/components/pagination/template.njk
  packages/govuk-frontend/src/govuk/components/pagination/template.test.js
Labels: nunjucks

#4745 Fix Nunjucks HTML indentation: Header
  packages/govuk-frontend/src/govuk/components/header/template.njk
  packages/govuk-frontend/src/govuk/components/header/template.test.js
Labels: nunjucks

#4676 Fix Nunjucks HTML indentation: Radios and Checkboxes
  packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
  packages/govuk-frontend/src/govuk/components/radios/template.njk
Labels: nunjucks

#4760 Move Review app confirmation pages to `/confirm` URL paths etc
  packages/govuk-frontend-review/src/app.mjs
  packages/govuk-frontend-review/src/common/lib/files.mjs
  packages/govuk-frontend-review/src/routes/full-page-examples.mjs
  packages/govuk-frontend-review/src/utils.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/announcements/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/bank-holidays/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/campaign-page/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/check-your-answers/confirm.njk
  packages/govuk-frontend-review/src/views/full-page-examples/check-your-answers/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/check-your-answers/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-essential-cookies/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-essential-cookies/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-server-side/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-server-side/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/feedback/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/have-you-changed-your-name/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/have-you-changed-your-name/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/how-do-you-want-to-sign-in/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/how-do-you-want-to-sign-in/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/passport-details/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/search/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/search/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/start-page/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/travel-guidance/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/update-your-account-details/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo-success/confirm.njk
  packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo-success/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo-success/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/confirm.njk
  packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-address/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-address/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-nationality/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-nationality/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-postcode/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-postcode/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/what-was-the-last-country-you-visited/index.mjs
  packages/govuk-frontend-review/src/views/full-page-examples/what-was-the-last-country-you-visited/index.njk
  packages/govuk-frontend-review/src/views/full-page-examples/work-history/index.njk
  packages/govuk-frontend-review/src/views/index.njk
Labels: assurance, nunjucks

#4766 Fix: automated axe testing custom options overridden by later configuration
  packages/govuk-frontend/src/govuk/components/accordion/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/button/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/cookie-banner/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/details/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/exit-this-page/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/header/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/hint/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/notification-banner/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/pagination/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/phase-banner/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/summary-list/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/tabs/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/tag/accessibility.puppeteer.test.mjs
  packages/govuk-frontend/src/govuk/components/task-list/accessibility.puppeteer.test.mjs
  shared/helpers/puppeteer.js
Labels: 🐛 bug

#4767 Fix Nunjucks HTML indentation: Task list, Tag
  packages/govuk-frontend/src/govuk/components/tag/template.njk
  packages/govuk-frontend/src/govuk/components/task-list/template.njk
  packages/govuk-frontend/src/govuk/components/task-list/template.test.js
Labels: nunjucks

#4743 Update macro `govukAttributes()` to support optional attributes
  packages/govuk-frontend/src/govuk/macros/attributes.njk
  packages/govuk-frontend/src/govuk/macros/attributes.unit.test.mjs
Labels: nunjucks
